/**
 * Food synonyms in all languages
 * Maps foreign language keywords to Spanish search terms for database matching
 */

export const FOOD_SYNONYMS: Record<string, string[]> = {
  // ==================== ENGLISH SYNONYMS ====================
  'chicken': ['pollo'],
  'beef': ['res', 'carne', 'bistec'],
  'pork': ['cerdo', 'puerco', 'carnitas'],
  'shrimp': ['camarón', 'camaron'],
  'fish': ['pescado', 'pescado'],
  'tuna': ['atún', 'atun'],
  'salmon': ['salmón', 'salmon'],
  'corn': ['maíz', 'maiz', 'elote'],
  'beans': ['frijol', 'frijoles'],
  'rice': ['arroz'],
  'egg': ['huevo'],
  'eggs': ['huevo'],
  'cheese': ['queso'],
  'avocado': ['aguacate'],
  'tomato': ['tomate', 'jitomate'],
  'onion': ['cebolla'],
  'pepper': ['chile', 'pimiento'],
  'garlic': ['ajo'],
  'cilantro': ['cilantro'],
  'lime': ['limón', 'limon'],
  'lemon': ['limón', 'limon'],
  'milk': ['leche'],
  'water': ['agua'],
  'coffee': ['café', 'cafe'],
  'tea': ['té', 'te'],
  'bread': ['pan', 'bolillo'],
  'tortilla': ['tortilla'],
  'taco': ['taco'],
  'burrito': ['burrito'],
  'quesadilla': ['quesadilla'],
  'enchilada': ['enchilada'],
  'salsa': ['salsa'],
  'guacamole': ['guacamole'],
  'nachos': ['nachos', 'totopos'],
  'soup': ['sopa', 'caldo'],
  'meat': ['carne'],
  'steak': ['bistec', 'carne asada'],
  'chili': ['chile'],
  'chocolate': ['chocolate'],
  'sugar': ['azúcar', 'azucar'],
  'salt': ['sal'],
  'oil': ['aceite'],
  'butter': ['mantequilla'],
  'cream': ['crema'],
  'flour': ['harina'],
  'peanut': ['cacahuate', 'cacahuete', 'cacahuates'],
  'peanuts': ['cacahuate', 'cacahuates'],
  'almond': ['almendra'],
  'walnut': ['nuez'],
  'mushroom': ['champiñón', 'champinon', 'hongo'],
  'mushrooms': ['champiñón', 'champiñones'],
  'lettuce': ['lechuga'],
  'carrot': ['zanahoria'],
  'potato': ['papa'],
  'potatoes': ['papa'],
  'sweet potato': ['camote'],
  'pumpkin': ['calabaza'],
  'banana': ['plátano', 'platano'],
  'apple': ['manzana'],
  'orange': ['naranja'],
  'strawberry': ['fresa'],
  'grape': ['uva'],
  'watermelon': ['sandía', 'sandia'],
  'mango': ['mango'],
  'papaya': ['papaya'],
  'pineapple': ['piña', 'pina'],
  'coconut': ['coco'],
  'dessert': ['postre', 'flan'],
  'ice cream': ['helado', 'nieve'],
  'cake': ['pastel'],
  'cookie': ['galleta'],
  'candy': ['dulce', 'cocada'],
  'breakfast': ['desayuno', 'huevos'],
  'lunch': ['comida', 'almuerzo'],
  'dinner': ['cena'],
  'snack': ['botana', 'snack'],

  // ==================== FRENCH SYNONYMS ====================
  'poulet': ['pollo'],
  'boeuf': ['res', 'carne'],
  'porc': ['cerdo', 'puerco'],
  'crevette': ['camarón', 'camaron'],
  'poisson': ['pescado'],
  'maïs': ['maíz', 'maiz'],
  'haricot': ['frijol'],
  'riz': ['arroz'],
  'oeuf': ['huevo'],
  'fromage': ['queso'],
  'avocat': ['aguacate'],
  'tomate': ['tomate'],
  'oignon': ['cebolla'],
  'citron': ['limón', 'limon'],
  'lait': ['leche'],
  'eau': ['agua'],
  'pain': ['pan'],
  'soupe': ['sopa', 'caldo'],
  'viande': ['carne'],
  'arachide': ['cacahuate'],
  'champignon': ['champiñón', 'champinon'],
  'pomme': ['manzana'],
  'fraise': ['fresa'],
  'pastèque': ['sandía', 'sandia'],
  'ananas': ['piña', 'pina'],

  // ==================== GERMAN SYNONYMS ====================
  'hähnchen': ['pollo'],
  'huhn': ['pollo'],
  'rind': ['res', 'carne'],
  'schwein': ['cerdo', 'puerco'],
  'garnele': ['camarón', 'camaron'],
  'fisch': ['pescado'],
  'mais': ['maíz', 'maiz'],
  'bohne': ['frijol'],
  'reis': ['arroz'],
  'ei': ['huevo'],
  'käse': ['queso'],
  'avocado': ['aguacate'],
  'tomate': ['tomate'],
  'zwiebel': ['cebolla'],
  'zitrone': ['limón', 'limon'],
  'milch': ['leche'],
  'wasser': ['acqua'],
  'brot': ['pan'],
  'suppe': ['sopa', 'caldo'],
  'fleisch': ['carne'],
  'erdnuss': ['cacahuate'],
  'champignon': ['champiñón', 'champinon'],
  'kartoffel': ['papa'],
  'apfel': ['manzana'],
  'erdbeere': ['fresa'],
  'wassermelone': ['sandía', 'sandia'],
  'ananas': ['piña', 'pina'],

  // ==================== PORTUGUESE SYNONYMS ====================
  'frango': ['pollo'],
  'carne': ['res', 'carne'],
  'porco': ['cerdo', 'puerco'],
  'camarão': ['camarón', 'camaron'],
  'peixe': ['pescado'],
  'milho': ['maíz', 'maiz', 'elote'],
  'feijão': ['frijol'],
  'arroz': ['arroz'],
  'ovo': ['huevo'],
  'queijo': ['queso'],
  'abacate': ['aguacate'],
  'tomate': ['tomate'],
  'cebola': ['cebolla'],
  'limão': ['limón', 'limon'],
  'leite': ['leche'],
  'água': ['agua'],
  'pão': ['pan'],
  'sopa': ['sopa', 'caldo'],
  'amendoim': ['cacahuate'],
  'cogumelo': ['champiñón', 'champinon'],
  'batata': ['papa'],
  'maçã': ['manzana'],
  'morango': ['fresa'],
  'melancia': ['sandía', 'sandia'],
  'abacaxi': ['piña', 'pina'],

  // ==================== ITALIAN SYNONYMS ====================
  'pollo': ['pollo'],
  'manzo': ['res', 'carne'],
  'maiale': ['cerdo', 'puerco'],
  'gamberi': ['camarón', 'camaron'],
  'pesce': ['pescado'],
  'mais': ['maíz', 'maiz'],
  'fagioli': ['frijol'],
  'riso': ['arroz'],
  'uovo': ['huevo'],
  'formaggio': ['queso'],
  'avocado': ['aguacate'],
  'pomodoro': ['tomate'],
  'cipolla': ['cebolla'],
  'limone': ['limón', 'limon'],
  'latte': ['leche'],
  'acqua': ['agua'],
  'pane': ['pan'],
  'zuppa': ['sopa', 'caldo'],
  'carne': ['carne'],
  'arachide': ['cacahuate'],
  'fungo': ['champiñón', 'champinon'],
  'patata': ['papa'],
  'mela': ['manzana'],
  'fragola': ['fresa'],
  'anguria': ['sandía', 'sandia'],
  'ananas': ['piña', 'pina'],

  // ==================== CHINESE SYNONYMS ====================
  '鸡': ['pollo'],
  '鸡肉': ['pollo'],
  '牛': ['res'],
  '牛肉': ['res', 'carne'],
  '猪': ['cerdo'],
  '猪肉': ['cerdo', 'puerco'],
  '虾': ['camarón', 'camaron'],
  '鱼': ['pescado'],
  '玉米': ['maíz', 'maiz', 'elote'],
  '豆': ['frijol'],
  '米饭': ['arroz'],
  '蛋': ['huevo'],
  '鸡蛋': ['huevo'],
  '奶酪': ['queso'],
  '牛油果': ['aguacate'],
  '番茄': ['tomate'],
  '洋葱': ['cebolla'],
  '柠檬': ['limón', 'limon'],
  '牛奶': ['leche'],
  '水': ['agua'],
  '咖啡': ['café', 'cafe'],
  '面包': ['pan'],
  '汤': ['sopa', 'caldo'],
  '肉': ['carne'],
  '花生': ['cacahuate'],
  '蘑菇': ['champiñón', 'champinon'],
  '土豆': ['papa'],
  '苹果': ['manzana'],
  '草莓': ['fresa'],
  '西瓜': ['sandía', 'sandia'],
  '芒果': ['mango'],
  '菠萝': ['piña', 'pina'],
  '椰子': ['coco'],

  // ==================== JAPANESE SYNONYMS ====================
  '鶏': ['pollo'],
  '鳥': ['pollo'],
  '牛肉': ['res', 'carne'],
  '豚': ['cerdo', 'puerco'],
  'エビ': ['camarón', 'camaron'],
  '魚': ['pescado'],
  'とうもろこし': ['maíz', 'maiz'],
  '豆': ['frijol'],
  '米': ['arroz'],
  '卵': ['huevo'],
  'チーズ': ['queso'],
  'アボカド': ['aguacate'],
  'トマト': ['tomate'],
  '玉ねぎ': ['cebolla'],
  'レモン': ['limón', 'limon'],
  '牛乳': ['leche'],
  '水': ['agua'],
  'コーヒー': ['café', 'cafe'],
  'パン': ['pan'],
  'スープ': ['sopa', 'caldo'],
  '肉': ['carne'],
  'ピーナッツ': ['cacahuate'],
  'マッシュルーム': ['champiñón', 'champinon'],
  'じゃがいも': ['papa'],
  'リンゴ': ['manzana'],
  'いちご': ['fresa'],
  'スイカ': ['sandía', 'sandia'],
  'マンゴー': ['mango'],
  'パイナップル': ['piña', 'pina'],

  // ==================== KOREAN SYNONYMS ====================
  '닭': ['pollo'],
  '닭고기': ['pollo'],
  '소고기': ['res', 'carne'],
  '돼지': ['cerdo', 'puerco'],
  '새우': ['camarón', 'camaron'],
  '생선': ['pescado'],
  '옥수수': ['maíz', 'maiz', 'elote'],
  '콩': ['frijol'],
  '밥': ['arroz'],
  '계란': ['huevo'],
  '치즈': ['queso'],
  '아보카도': ['aguacate'],
  '토마토': ['tomate'],
  '양파': ['cebolla'],
  '레몬': ['limón', 'limon'],
  '우유': ['leche'],
  '물': ['agua'],
  '커피': ['café', 'cafe'],
  '빵': ['pan'],
  '수프': ['sopa', 'caldo'],
  '고기': ['carne'],
  '땅콩': ['cacahuate'],
  '버섯': ['champiñón', 'champinon'],
  '감자': ['papa'],
  '사과': ['manzana'],
  '딸기': ['fresa'],
  '수박': ['sandía', 'sandia'],
  '망고': ['mango'],
  '파인애플': ['piña', 'pina'],

  // ==================== ARABIC SYNONYMS ====================
  'دجاج': ['pollo'],
  'لحم': ['res', 'carne'],
  'خنزير': ['cerdo', 'puerco'],
  'روبيان': ['camarón', 'camaron'],
  'سمك': ['pescado'],
  'ذرة': ['maíz', 'maiz'],
  'فاصوليا': ['frijol'],
  'أرز': ['arroz'],
  'بيض': ['huevo'],
  'جبنة': ['queso'],
  'أفوكادو': ['aguacate'],
  'طماطم': ['tomate'],
  'بصل': ['cebolla'],
  'ليمون': ['limón', 'limon'],
  'حليب': ['leche'],
  'ماء': ['agua'],
  'قهوة': ['café', 'cafe'],
  'خبز': ['pan'],
  'شوربة': ['sopa', 'caldo'],
  'فول سوداني': ['cacahuate'],
  'فطر': ['champiñón', 'champinon'],
  'بطاطس': ['papa'],
  'تفاح': ['manzana'],
  'فراولة': ['fresa'],
  'بطيخ': ['sandía', 'sandia'],
  'أناناس': ['piña', 'pina'],

  // ==================== HINDI SYNONYMS ====================
  'चिकन': ['pollo'],
  'मांस': ['res', 'carne'],
  'सूअर': ['cerdo', 'puerco'],
  'झींगा': ['camarón', 'camaron'],
  'मछली': ['pescado'],
  'मक्का': ['maíz', 'maiz'],
  'सेम': ['frijol'],
  'चावल': ['arroz'],
  'अंडा': ['huevo'],
  'पनीर': ['queso'],
  'एवोकैडो': ['aguacate'],
  'टमाटर': ['tomate'],
  'प्याज': ['cebolla'],
  'नींबू': ['limón', 'limon'],
  'दूध': ['leche'],
  'पानी': ['agua'],
  'कॉफी': ['café', 'cafe'],
  'रोटी': ['pan'],
  'सूप': ['sopa', 'caldo'],
  'मूंगफली': ['cacahuate'],
  'मशरूम': ['champiñón', 'champinon'],
  'आलू': ['papa'],
  'सेब': ['manzana'],
  'स्ट्रॉबेरी': ['fresa'],
  'तरबूज': ['sandía', 'sandia'],
  'आम': ['mango'],
  'अनानास': ['piña', 'pina'],

  // ==================== RUSSIAN SYNONYMS ====================
  'курица': ['pollo'],
  'говядина': ['res', 'carne'],
  'свинина': ['cerdo', 'puerco'],
  'креветка': ['camarón', 'camaron'],
  'рыба': ['pescado'],
  'кукуруза': ['maíz', 'maiz'],
  'фасоль': ['frijol'],
  'рис': ['arроз'],
  'яйцо': ['huevo'],
  'сыр': ['queso'],
  'авокадо': ['aguacate'],
  'помидор': ['tomate'],
  'лук': ['cebolla'],
  'лимон': ['limón', 'limon'],
  'молоко': ['leche'],
  'вода': ['agua'],
  'кофе': ['café', 'cafe'],
  'хлеб': ['pan'],
  'суп': ['sopa', 'caldo'],
  'мясо': ['carne'],
  'арахис': ['cacahuate'],
  'гриб': ['champiñón', 'champinon'],
  'картофель': ['papa'],
  'яблоко': ['manzana'],
  'клубника': ['fresa'],
  'арбуз': ['sandía', 'sandia'],
  'манго': ['mango'],
  'ананас': ['piña', 'pina'],
};

/**
 * Get Spanish search terms for a given foreign language keyword
 * Returns array of Spanish terms to search for
 */
export function getSpanishSearchTerms(query: string): string[] {
  const normalizedQuery = query.toLowerCase().trim();

  // Check if it's a known synonym
  if (FOOD_SYNONYMS[normalizedQuery]) {
    return FOOD_SYNONYMS[normalizedQuery];
  }

  // Check partial matches
  const matches: string[] = [];
  for (const [synonym, spanishTerms] of Object.entries(FOOD_SYNONYMS)) {
    if (normalizedQuery.includes(synonym) || synonym.includes(normalizedQuery)) {
      matches.push(...spanishTerms);
    }
  }

  // If no matches found, return original query (assume it might be Spanish)
  return matches.length > 0 ? [...new Set(matches)] : [normalizedQuery];
}
