/**
 * Base de datos de alimentos comunes en español
 * Para uso offline y autocompletado rápido
 */

export interface FoodItem {
  id: string;
  name: string;
  category: string;
  calories: number; // por 100g
  protein: number; // gramos por 100g
  carbs: number; // gramos por 100g
  fat: number; // gramos por 100g
  fiber: number; // gramos por 100g
  servingSize: number; // porción común en gramos
  servingName: string; // nombre de la porción
}

export const FOOD_DATABASE: FoodItem[] = [
  // Frutas
  {
    id: 'fruit-001',
    name: 'Manzana',
    category: 'frutas',
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
    servingSize: 182,
    servingName: '1 mediana',
  },
  {
    id: 'fruit-002',
    name: 'Plátano/Banana',
    category: 'frutas',
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    servingSize: 118,
    servingName: '1 mediano',
  },
  {
    id: 'fruit-003',
    name: 'Naranja',
    category: 'frutas',
    calories: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    fiber: 2.4,
    servingSize: 131,
    servingName: '1 mediana',
  },
  {
    id: 'fruit-004',
    name: 'Fresas',
    category: 'frutas',
    calories: 32,
    protein: 0.7,
    carbs: 8,
    fat: 0.3,
    fiber: 2,
    servingSize: 150,
    servingName: '1 taza',
  },
  {
    id: 'fruit-005',
    name: 'Uvas',
    category: 'frutas',
    calories: 67,
    protein: 0.6,
    carbs: 17,
    fat: 0.4,
    fiber: 0.9,
    servingSize: 151,
    servingName: '1 taza',
  },

  // Verduras
  {
    id: 'veg-001',
    name: 'Brócoli',
    category: 'verduras',
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    fiber: 2.6,
    servingSize: 91,
    servingName: '1 taza',
  },
  {
    id: 'veg-002',
    name: 'Espinaca',
    category: 'verduras',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    servingSize: 30,
    servingName: '1 taza',
  },
  {
    id: 'veg-003',
    name: 'Zanahoria',
    category: 'verduras',
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    fiber: 2.8,
    servingSize: 61,
    servingName: '1 mediana',
  },
  {
    id: 'veg-004',
    name: 'Tomate',
    category: 'verduras',
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    servingSize: 123,
    servingName: '1 mediano',
  },
  {
    id: 'veg-005',
    name: 'Lechuga',
    category: 'verduras',
    calories: 15,
    protein: 1.4,
    carbs: 2.9,
    fat: 0.2,
    fiber: 1.3,
    servingSize: 55,
    servingName: '1 taza',
  },

  // Proteínas
  {
    id: 'protein-001',
    name: 'Pechuga de Pollo',
    category: 'proteinas',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    servingSize: 140,
    servingName: '1 filete',
  },
  {
    id: 'protein-002',
    name: 'Carne de Res (Magro)',
    category: 'proteinas',
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 15,
    fiber: 0,
    servingSize: 100,
    servingName: '100g',
  },
  {
    id: 'protein-003',
    name: 'Salmón',
    category: 'proteinas',
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    fiber: 0,
    servingSize: 150,
    servingName: '1 filete',
  },
  {
    id: 'protein-004',
    name: 'Atún en Agua',
    category: 'proteinas',
    calories: 116,
    protein: 26,
    carbs: 0,
    fat: 1,
    fiber: 0,
    servingSize: 100,
    servingName: '1 lata',
  },
  {
    id: 'protein-005',
    name: 'Huevo',
    category: 'proteinas',
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    servingSize: 50,
    servingName: '1 grande',
  },
  {
    id: 'protein-006',
    name: 'Huevo Frito',
    category: 'proteinas',
    calories: 196,
    protein: 13,
    carbs: 1.1,
    fat: 15,
    fiber: 0,
    servingSize: 50,
    servingName: '1 unidad',
  },

  // Carbohidratos
  {
    id: 'carb-001',
    name: 'Arroz Blanco',
    category: 'carbohidratos',
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    servingSize: 158,
    servingName: '1 taza',
  },
  {
    id: 'carb-002',
    name: 'Arroz Integral',
    category: 'carbohidratos',
    calories: 111,
    protein: 2.6,
    carbs: 23,
    fat: 0.9,
    fiber: 1.8,
    servingSize: 195,
    servingName: '1 taza',
  },
  {
    id: 'carb-003',
    name: 'Pasta',
    category: 'carbohidratos',
    calories: 131,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    fiber: 1.8,
    servingSize: 140,
    servingName: '1 taza',
  },
  {
    id: 'carb-004',
    name: 'Papa/Patata',
    category: 'carbohidratos',
    calories: 77,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    fiber: 2.2,
    servingSize: 173,
    servingName: '1 mediana',
  },
  {
    id: 'carb-005',
    name: 'Pan Blanco',
    category: 'carbohidratos',
    calories: 265,
    protein: 9,
    carbs: 49,
    fat: 3.2,
    fiber: 2.7,
    servingSize: 30,
    servingName: '1 rebanada',
  },
  {
    id: 'carb-006',
    name: 'Pan Integral',
    category: 'carbohidratos',
    calories: 247,
    protein: 13,
    carbs: 41,
    fat: 3.4,
    fiber: 7,
    servingSize: 30,
    servingName: '1 rebanada',
  },
  {
    id: 'carb-007',
    name: 'Avena',
    category: 'carbohidratos',
    calories: 68,
    protein: 2.4,
    carbs: 12,
    fat: 1.4,
    fiber: 1.7,
    servingSize: 234,
    servingName: '1 taza cocida',
  },

  // Lácteos
  {
    id: 'dairy-001',
    name: 'Leche Entera',
    category: 'lacteos',
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
    servingSize: 244,
    servingName: '1 vaso',
  },
  {
    id: 'dairy-002',
    name: 'Leche Descremada',
    category: 'lacteos',
    calories: 34,
    protein: 3.4,
    carbs: 5,
    fat: 0.1,
    fiber: 0,
    servingSize: 245,
    servingName: '1 vaso',
  },
  {
    id: 'dairy-003',
    name: 'Yogur Natural',
    category: 'lacteos',
    calories: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    fiber: 0,
    servingSize: 170,
    servingName: '1 envase',
  },
  {
    id: 'dairy-004',
    name: 'Yogur Griego',
    category: 'lacteos',
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0,
    servingSize: 170,
    servingName: '1 envase',
  },
  {
    id: 'dairy-005',
    name: 'Queso Cheddar',
    category: 'lacteos',
    calories: 403,
    protein: 25,
    carbs: 1.3,
    fat: 33,
    fiber: 0,
    servingSize: 30,
    servingName: '1 rebanada',
  },
  {
    id: 'dairy-006',
    name: 'Queso Fresco',
    category: 'lacteos',
    calories: 280,
    protein: 18,
    carbs: 4,
    fat: 21,
    fiber: 0,
    servingSize: 30,
    servingName: '1 rebanada',
  },

  // Frutos Secos
  {
    id: 'nuts-001',
    name: 'Almendras',
    category: 'frutos_secos',
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 12,
    servingSize: 28,
    servingName: '1 puñado',
  },
  {
    id: 'nuts-002',
    name: 'Nueces',
    category: 'frutos_secos',
    calories: 654,
    protein: 15,
    carbs: 14,
    fat: 65,
    fiber: 7,
    servingSize: 30,
    servingName: '1 puñado',
  },
  {
    id: 'nuts-003',
    name: 'Maní/Cacahuate',
    category: 'frutos_secos',
    calories: 567,
    protein: 26,
    carbs: 16,
    fat: 49,
    fiber: 8,
    servingSize: 28,
    servingName: '1 puñado',
  },

  // Bebidas
  {
    id: 'drink-001',
    name: 'Agua',
    category: 'bebidas',
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    servingSize: 250,
    servingName: '1 vaso',
  },
  {
    id: 'drink-002',
    name: 'Café Solo',
    category: 'bebidas',
    calories: 2,
    protein: 0.3,
    carbs: 0,
    fat: 0,
    fiber: 0,
    servingSize: 240,
    servingName: '1 taza',
  },
  {
    id: 'drink-003',
    name: 'Café con Leche',
    category: 'bebidas',
    calories: 50,
    protein: 3,
    carbs: 5,
    fat: 2,
    fiber: 0,
    servingSize: 240,
    servingName: '1 taza',
  },
  {
    id: 'drink-004',
    name: 'Jugo de Naranja',
    category: 'bebidas',
    calories: 45,
    protein: 0.7,
    carbs: 10,
    fat: 0.2,
    fiber: 0.2,
    servingSize: 248,
    servingName: '1 vaso',
  },
  {
    id: 'drink-005',
    name: 'Refresco/Gaseosa',
    category: 'bebidas',
    calories: 42,
    protein: 0,
    carbs: 11,
    fat: 0,
    fiber: 0,
    servingSize: 355,
    servingName: '1 lata',
  },

  // Snacks
  {
    id: 'snack-001',
    name: 'Papas Fritas',
    category: 'snacks',
    calories: 536,
    protein: 7,
    carbs: 53,
    fat: 34,
    fiber: 5,
    servingSize: 28,
    servingName: '1 puñado',
  },
  {
    id: 'snack-002',
    name: 'Chocolate con Leche',
    category: 'snacks',
    calories: 535,
    protein: 8,
    carbs: 59,
    fat: 30,
    fiber: 3,
    servingSize: 40,
    servingName: '1 barra',
  },
  {
    id: 'snack-003',
    name: 'Chocolate Amargo',
    category: 'snacks',
    calories: 598,
    protein: 8,
    carbs: 46,
    fat: 43,
    fiber: 11,
    servingSize: 40,
    servingName: '1 barra',
  },
  {
    id: 'snack-004',
    name: 'Galletas',
    category: 'snacks',
    calories: 450,
    protein: 7,
    carbs: 68,
    fat: 16,
    fiber: 2,
    servingSize: 30,
    servingName: '3-4 unidades',
  },

  // Comida Rápida
  {
    id: 'fast-001',
    name: 'Hamburguesa',
    category: 'comida_rapida',
    calories: 295,
    protein: 17,
    carbs: 30,
    fat: 12,
    fiber: 2,
    servingSize: 100,
    servingName: '1 unidad',
  },
  {
    id: 'fast-002',
    name: 'Pizza (Pepperoni)',
    category: 'comida_rapida',
    calories: 298,
    protein: 12,
    carbs: 33,
    fat: 13,
    fiber: 2,
    servingSize: 107,
    servingName: '1 rebanada',
  },
  {
    id: 'fast-003',
    name: 'Tacos',
    category: 'comida_rapida',
    calories: 210,
    protein: 9,
    carbs: 20,
    fat: 11,
    fiber: 3,
    servingSize: 85,
    servingName: '1 unidad',
  },
  {
    id: 'fast-004',
    name: 'Ensalada César',
    category: 'comida_rapida',
    calories: 184,
    protein: 7,
    carbs: 7,
    fat: 15,
    fiber: 2,
    servingSize: 243,
    servingName: '1 plato',
  },

  // Legumbres
  {
    id: 'legume-001',
    name: 'Frijoles/Porotos',
    category: 'legumbres',
    calories: 127,
    protein: 8.7,
    carbs: 23,
    fat: 0.5,
    fiber: 6.4,
    servingSize: 177,
    servingName: '1 taza',
  },
  {
    id: 'legume-002',
    name: 'Lentejas',
    category: 'legumbres',
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    fiber: 7.9,
    servingSize: 198,
    servingName: '1 taza',
  },
  {
    id: 'legume-003',
    name: 'Garbanzos',
    category: 'legumbres',
    calories: 164,
    protein: 8.9,
    carbs: 27,
    fat: 2.6,
    fiber: 7.6,
    servingSize: 164,
    servingName: '1 taza',
  },
];

import Fuse from 'fuse.js';

const fuseOptions = {
  keys: ['name', 'category'],
  threshold: 0.3, // Tolerancia a typos (0.0 es exacto, 1.0 es todo)
  distance: 50,
};

const fuse = new Fuse(FOOD_DATABASE, fuseOptions);

// Función para buscar alimentos
export function searchFoods(query: string): FoodItem[] {
  if (!query.trim()) return [];
  
  return fuse.search(query).map(result => result.item).slice(0, 10);
}

// Función para obtener alimento por ID
export function getFoodById(id: string): FoodItem | undefined {
  return FOOD_DATABASE.find(food => food.id === id);
}

// Función para obtener alimentos frecuentes (simulado)
export function getFrequentFoods(): FoodItem[] {
  // En producción, esto vendría del historial del usuario
  return FOOD_DATABASE.slice(0, 8);
}

// Función para obtener alimentos por categoría
export function getFoodsByCategory(category: string): FoodItem[] {
  return FOOD_DATABASE.filter(food => food.category === category);
}
