import mysql from 'mysql2/promise';
import { randomUUID } from 'crypto';

const FOODS = [
  // ==================== ESTADOS UNIDOS ====================
  { name: 'Hamburguesa clásica', brand: null, calories: 295, protein: 17, carbs: 24, fat: 14, fiber: 1, serving_size: 1, serving_name: 'pieza (215g)', category: 'Americana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan de hamburguesa, carne de res, lechuga, tomate, cebolla, pepinillos, ketchup, mostaza', data_source: 'USDA FoodData Central' },
  { name: 'Hamburguesa con queso', brand: null, calories: 325, protein: 19, carbs: 26, fat: 16, fiber: 1, serving_size: 1, serving_name: 'pieza (230g)', category: 'Americana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan, carne de res, queso americano, lechuga, tomate, condimentos', data_source: 'USDA FoodData Central' },
  { name: 'Hamburguesa doble con tocino', brand: null, calories: 450, protein: 28, carbs: 28, fat: 26, fiber: 1, serving_size: 1, serving_name: 'pieza (300g)', category: 'Americana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan, doble carne, tocino, queso, lechuga, tomate, salsa especial', data_source: 'USDA FoodData Central' },
  { name: 'Hot dog clásico', brand: null, calories: 290, protein: 11, carbs: 24, fat: 17, fiber: 1, serving_size: 1, serving_name: 'pieza (140g)', category: 'Americana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan de hot dog, salchicha, ketchup, mostaza, relish', data_source: 'USDA FoodData Central' },
  { name: 'Hot dog con chili', brand: null, calories: 350, protein: 15, carbs: 30, fat: 18, fiber: 3, serving_size: 1, serving_name: 'pieza (180g)', category: 'Americana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan, salchicha, chili con carne, queso cheddar, cebolla', data_source: 'USDA FoodData Central' },
  { name: 'Mac and Cheese', brand: null, calories: 280, protein: 12, carbs: 32, fat: 12, fiber: 2, serving_size: 1, serving_name: 'taza (200g)', category: 'Americana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Macarrones, queso cheddar, mantequilla, leche, pan molido', data_source: 'USDA FoodData Central' },
  { name: 'Pollo frito estilo sureño', brand: null, calories: 320, protein: 22, carbs: 16, fat: 20, fiber: 1, serving_size: 1, serving_name: 'pieza (150g)', category: 'Americana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pollo, harina, huevo, suero de mantequilla, especias, aceite', data_source: 'USDA FoodData Central' },
  { name: 'BBQ Ribs (costillas BBQ)', brand: null, calories: 360, protein: 24, carbs: 18, fat: 22, fiber: 0, serving_size: 1, serving_name: 'porción (200g)', category: 'Americana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Costillas de cerdo, salsa BBQ, azúcar morena, vinagre, especias', data_source: 'USDA FoodData Central' },
  { name: 'Buffalo Wings', brand: null, calories: 290, protein: 18, carbs: 2, fat: 24, fiber: 0, serving_size: 6, serving_name: 'piezas (150g)', category: 'Americana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Alitas de pollo, salsa buffalo, mantequilla, vinagre, aderezo ranch', data_source: 'USDA FoodData Central' },
  { name: 'Philly Cheesesteak', brand: null, calories: 520, protein: 30, carbs: 42, fat: 24, fiber: 2, serving_size: 1, serving_name: 'sándwich (300g)', category: 'Americana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan, carne de res en tiras, queso provolone, pimientos, cebolla', data_source: 'USDA FoodData Central' },
  { name: 'Reuben Sandwich', brand: null, calories: 480, protein: 25, carbs: 35, fat: 26, fiber: 3, serving_size: 1, serving_name: 'sándwich (280g)', category: 'Americana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Pan de centeno, pastrami, chucrut, queso suizo, salsa rusa', data_source: 'USDA FoodData Central' },
  { name: 'Cobb Salad', brand: null, calories: 350, protein: 28, carbs: 10, fat: 24, fiber: 4, serving_size: 1, serving_name: 'ensalada (350g)', category: 'Americana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Lechuga, pollo, tocino, huevo, aguacate, queso azul, tomate, aderezo ranch', data_source: 'USDA FoodData Central' },
  { name: 'Caesar Salad', brand: null, calories: 220, protein: 8, carbs: 12, fat: 16, fiber: 3, serving_size: 1, serving_name: 'ensalada (250g)', category: 'Americana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Lechuga romana, aderezo César, crutones, queso parmesano', data_source: 'USDA FoodData Central' },
  { name: 'New England Clam Chowder', brand: null, calories: 180, protein: 8, carbs: 18, fat: 9, fiber: 1, serving_size: 1, serving_name: 'tazón (300ml)', category: 'Americana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Almejas, papa, cebolla, apio, crema, mantequilla', data_source: 'USDA FoodData Central' },
  { name: 'Gumbo de mariscos', brand: null, calories: 250, protein: 15, carbs: 20, fat: 12, fiber: 2, serving_size: 1, serving_name: 'tazón (350ml)', category: 'Americana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Camarón, cangrejo, okra, arroz, roux, salchicha, especias cajún', data_source: 'USDA FoodData Central' },
  { name: 'Jambalaya', brand: null, calories: 320, protein: 18, carbs: 35, fat: 12, fiber: 2, serving_size: 1, serving_name: 'plato (300g)', category: 'Americana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Arroz, salchicha andouille, pollo, camarón, pimiento, apio, tomate', data_source: 'USDA FoodData Central' },
  { name: 'Po-Boy de camarón', brand: null, calories: 480, protein: 20, carbs: 50, fat: 22, fiber: 2, serving_size: 1, serving_name: 'sándwich (280g)', category: 'Americana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Pan francés, camarón frito, lechuga, tomate, mayonesa', data_source: 'USDA FoodData Central' },
  { name: 'Pulled Pork Sandwich', brand: null, calories: 520, protein: 28, carbs: 45, fat: 24, fiber: 2, serving_size: 1, serving_name: 'sándwich (300g)', category: 'Americana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan, cerdo desmenuzado, salsa BBQ, ensalada de col', data_source: 'USDA FoodData Central' },
  { name: 'Pancakes con jarabe de maple', brand: null, calories: 350, protein: 8, carbs: 55, fat: 12, fiber: 2, serving_size: 3, serving_name: 'piezas (200g)', category: 'Americana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Harina, huevo, leche, mantequilla, jarabe de maple, polvo para hornear', data_source: 'USDA FoodData Central' },
  { name: 'Waffles con mantequilla', brand: null, calories: 320, protein: 7, carbs: 42, fat: 14, fiber: 1, serving_size: 1, serving_name: 'pieza (150g)', category: 'Americana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Harina, huevo, leche, mantequilla, azúcar, polvo para hornear', data_source: 'USDA FoodData Central' },
  { name: 'Bagel con cream cheese', brand: null, calories: 350, protein: 10, carbs: 50, fat: 12, fiber: 2, serving_size: 1, serving_name: 'pieza (130g)', category: 'Americana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Bagel, queso crema, salmón (opcional)', data_source: 'USDA FoodData Central' },
  { name: 'Clamato (sangría)', brand: null, calories: 45, protein: 2, carbs: 7, fat: 0, fiber: 0, serving_size: 1, serving_name: 'vaso (250ml)', category: 'Americana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Jugo de almeja, tomate, especias', data_source: 'USDA FoodData Central' },
  { name: 'Apple Pie (pay de manzana)', brand: null, calories: 320, protein: 3, carbs: 45, fat: 14, fiber: 2, serving_size: 1, serving_name: 'rebanada (125g)', category: 'Americana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Manzana, harina, mantequilla, azúcar, canela, nuez moscada', data_source: 'USDA FoodData Central' },
  { name: 'Brownie de chocolate', brand: null, calories: 250, protein: 3, carbs: 35, fat: 12, fiber: 2, serving_size: 1, serving_name: 'pieza (60g)', category: 'Americana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Chocolate, mantequilla, azúcar, huevo, harina, cacao', data_source: 'USDA FoodData Central' },
  { name: 'Cheesecake de Nueva York', brand: null, calories: 380, protein: 8, carbs: 32, fat: 24, fiber: 0, serving_size: 1, serving_name: 'rebanada (120g)', category: 'Americana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Queso crema, galleta, mantequilla, azúcar, huevo, vainilla', data_source: 'USDA FoodData Central' },
  { name: 'Donut glaseado', brand: null, calories: 270, protein: 4, carbs: 32, fat: 14, fiber: 1, serving_size: 1, serving_name: 'pieza (70g)', category: 'Americana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Harina, azúcar, levadura, huevo, mantequilla, glaseado', data_source: 'USDA FoodData Central' },
  { name: 'Muffin de arándanos', brand: null, calories: 320, protein: 5, carbs: 48, fat: 12, fiber: 2, serving_size: 1, serving_name: 'pieza (110g)', category: 'Americana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Harina, arándanos, azúcar, mantequilla, huevo, leche', data_source: 'USDA FoodData Central' },

  // ==================== ITALIA ====================
  { name: 'Pizza Margherita', brand: null, calories: 266, protein: 11, carbs: 33, fat: 10, fiber: 2, serving_size: 1, serving_name: 'rebanada (150g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa de pizza, salsa de tomate, mozzarella fresca, albahaca, aceite de oliva', data_source: 'BDA-IEO' },
  { name: 'Pizza Pepperoni', brand: null, calories: 298, protein: 13, carbs: 30, fat: 14, fiber: 2, serving_size: 1, serving_name: 'rebanada (150g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa, salsa de tomate, mozzarella, pepperoni', data_source: 'BDA-IEO' },
  { name: 'Pizza Quattro Formaggi', brand: null, calories: 312, protein: 14, carbs: 30, fat: 16, fiber: 2, serving_size: 1, serving_name: 'rebanada (150g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa, mozzarella, gorgonzola, parmesano, fontina', data_source: 'BDA-IEO' },
  { name: 'Spaghetti alla Carbonara', brand: null, calories: 410, protein: 18, carbs: 48, fat: 16, fiber: 2, serving_size: 1, serving_name: 'plato (300g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Spaghetti, huevo, pecorino romano, guanciale, pimienta negra', data_source: 'BDA-IEO' },
  { name: 'Spaghetti Bolognese', brand: null, calories: 380, protein: 20, carbs: 50, fat: 10, fiber: 3, serving_size: 1, serving_name: 'plato (350g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Spaghetti, carne molida, tomate, cebolla, zanahoria, apio, vino tinto', data_source: 'BDA-IEO' },
  { name: 'Spaghetti alle Vongole', brand: null, calories: 340, protein: 18, carbs: 45, fat: 8, fiber: 2, serving_size: 1, serving_name: 'plato (300g)', category: 'Italiana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Spaghetti, almejas, ajo, vino blanco, perejil, aceite de oliva', data_source: 'BDA-IEO' },
  { name: 'Penne all\'Arrabbiata', brand: null, calories: 320, protein: 10, carbs: 52, fat: 8, fiber: 3, serving_size: 1, serving_name: 'plato (280g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Penne, tomate, ajo, chile rojo, aceite de oliva, perejil', data_source: 'BDA-IEO' },
  { name: 'Fettuccine Alfredo', brand: null, calories: 480, protein: 14, carbs: 48, fat: 26, fiber: 2, serving_size: 1, serving_name: 'plato (300g)', category: 'Italiana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Fettuccine, mantequilla, parmesano, crema', data_source: 'BDA-IEO' },
  { name: 'Lasagna Bolognese', brand: null, calories: 350, protein: 20, carbs: 32, fat: 16, fiber: 3, serving_size: 1, serving_name: 'rebanada (250g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pasta, ragú bolognés, bechamel, parmesano, mozzarella', data_source: 'BDA-IEO' },
  { name: 'Risotto alla Milanese', brand: null, calories: 320, protein: 8, carbs: 48, fat: 10, fiber: 1, serving_size: 1, serving_name: 'plato (250g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz arborio, azafrán, caldo, mantequilla, parmesano, vino blanco', data_source: 'BDA-IEO' },
  { name: 'Risotto ai Funghi Porcini', brand: null, calories: 340, protein: 12, carbs: 48, fat: 12, fiber: 3, serving_size: 1, serving_name: 'plato (280g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz arborio, hongos porcini, caldo, mantequilla, parmesano', data_source: 'BDA-IEO' },
  { name: 'Gnocchi al Pesto', brand: null, calories: 380, protein: 12, carbs: 48, fat: 16, fiber: 2, serving_size: 1, serving_name: 'plato (280g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Gnocchi de papa, albahaca, piñones, parmesano, ajo, aceite de oliva', data_source: 'BDA-IEO' },
  { name: 'Ravioli de ricotta y espinaca', brand: null, calories: 320, protein: 14, carbs: 40, fat: 12, fiber: 2, serving_size: 1, serving_name: 'plato (250g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Ravioli, ricotta, espinaca, mantequilla, salvia, parmesano', data_source: 'BDA-IEO' },
  { name: 'Ossobuco alla Milanese', brand: null, calories: 420, protein: 35, carbs: 12, fat: 26, fiber: 2, serving_size: 1, serving_name: 'porción (300g)', category: 'Italiana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Chamorro de ternera, vino blanco, tomate, cebolla, zanahoria, gremolata', data_source: 'BDA-IEO' },
  { name: 'Saltimbocca alla Romana', brand: null, calories: 350, protein: 30, carbs: 5, fat: 24, fiber: 0, serving_size: 1, serving_name: 'porción (200g)', category: 'Italiana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Filete de ternera, jamón prosciutto, salvia, mantequilla, vino blanco', data_source: 'BDA-IEO' },
  { name: 'Pollo alla Parmigiana', brand: null, calories: 420, protein: 28, carbs: 25, fat: 24, fiber: 2, serving_size: 1, serving_name: 'porción (280g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pechuga empanizada, salsa de tomate, mozzarella, parmesano, albahaca', data_source: 'BDA-IEO' },
  { name: 'Bruschetta al Pomodoro', brand: null, calories: 150, protein: 4, carbs: 20, fat: 6, fiber: 2, serving_size: 2, serving_name: 'piezas (100g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan tostado, tomate, ajo, albahaca, aceite de oliva', data_source: 'BDA-IEO' },
  { name: 'Carpaccio di Manzo', brand: null, calories: 180, protein: 22, carbs: 2, fat: 10, fiber: 0, serving_size: 1, serving_name: 'plato (120g)', category: 'Italiana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Carne de res cruda en láminas, rúcula, parmesano, limón, aceite de oliva', data_source: 'BDA-IEO' },
  { name: 'Caprese (Mozzarella y Tomate)', brand: null, calories: 220, protein: 12, carbs: 6, fat: 18, fiber: 1, serving_size: 1, serving_name: 'plato (180g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Mozzarella fresca, tomate, albahaca, aceite de oliva, sal', data_source: 'BDA-IEO' },
  { name: 'Antipasto Misto', brand: null, calories: 280, protein: 14, carbs: 10, fat: 20, fiber: 2, serving_size: 1, serving_name: 'plato (200g)', category: 'Italiana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Jamón curado, salami, mozzarella, aceitunas, pimientos, alcachofas', data_source: 'BDA-IEO' },
  { name: 'Tiramisú', brand: null, calories: 280, protein: 6, carbs: 32, fat: 14, fiber: 0, serving_size: 1, serving_name: 'porción (120g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Bizcochos, mascarpone, café espresso, huevo, azúcar, cacao', data_source: 'BDA-IEO' },
  { name: 'Panna Cotta', brand: null, calories: 240, protein: 4, carbs: 20, fat: 16, fiber: 0, serving_size: 1, serving_name: 'porción (120g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Crema, azúcar, gelatina, vainilla, coulis de frutos rojos', data_source: 'BDA-IEO' },
  { name: 'Cannoli Siciliano', brand: null, calories: 320, protein: 8, carbs: 35, fat: 16, fiber: 1, serving_size: 1, serving_name: 'pieza (100g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa frita, ricotta, azúcar, chips de chocolate, pistache', data_source: 'BDA-IEO' },
  { name: 'Gelato de pistache', brand: null, calories: 220, protein: 6, carbs: 28, fat: 10, fiber: 1, serving_size: 1, serving_name: 'bola (100g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Leche, crema, azúcar, pistache, yema de huevo', data_source: 'BDA-IEO' },
  { name: 'Gelato de stracciatella', brand: null, calories: 210, protein: 5, carbs: 26, fat: 10, fiber: 0, serving_size: 1, serving_name: 'bola (100g)', category: 'Italiana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Leche, crema, azúcar, chocolate', data_source: 'BDA-IEO' },
  { name: 'Focaccia con romero', brand: null, calories: 230, protein: 5, carbs: 32, fat: 9, fiber: 1, serving_size: 1, serving_name: 'rebanada (100g)', category: 'Italiana', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Harina, levadura, aceite de oliva, romero, sal marina', data_source: 'BDA-IEO' },
  { name: 'Arancini (bolitas de arroz)', brand: null, calories: 280, protein: 10, carbs: 32, fat: 12, fiber: 2, serving_size: 2, serving_name: 'piezas (150g)', category: 'Italiana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Arroz, ragú, mozzarella, pan molido, huevo, aceite', data_source: 'BDA-IEO' },
  { name: 'Minestrone', brand: null, calories: 120, protein: 5, carbs: 18, fat: 3, fiber: 4, serving_size: 1, serving_name: 'tazón (300ml)', category: 'Italiana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Verduras mixtas, frijoles, pasta, tomate, caldo, parmesano', data_source: 'BDA-IEO' },
  { name: 'Pollo Cacciatore', brand: null, calories: 320, protein: 28, carbs: 12, fat: 18, fiber: 3, serving_size: 1, serving_name: 'porción (280g)', category: 'Italiana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Pollo, tomate, pimiento, cebolla, ajo, vino, hierbas', data_source: 'BDA-IEO' },
  { name: 'Vitello Tonnato', brand: null, calories: 280, protein: 25, carbs: 5, fat: 18, fiber: 0, serving_size: 1, serving_name: 'porción (200g)', category: 'Italiana', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Ternera fría, atún, alcaparras, mayonesa, limón', data_source: 'BDA-IEO' },

  // ==================== JAPÓN ====================
  { name: 'Sushi Nigiri de Salmón', brand: null, calories: 140, protein: 12, carbs: 18, fat: 2, fiber: 0, serving_size: 2, serving_name: 'piezas (80g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz para sushi, salmón fresco, vinagre de arroz, wasabi, jengibre', data_source: 'MEXT Japan Food Database' },
  { name: 'Sushi Nigiri de Atún', brand: null, calories: 130, protein: 14, carbs: 16, fat: 1, fiber: 0, serving_size: 2, serving_name: 'piezas (75g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz para sushi, atún maguro, vinagre de arroz, wasabi', data_source: 'MEXT Japan Food Database' },
  { name: 'Sushi Nigiri de Camarón', brand: null, calories: 120, protein: 10, carbs: 16, fat: 1, fiber: 0, serving_size: 2, serving_name: 'piezas (70g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz para sushi, camarón cocido, vinagre de arroz', data_source: 'MEXT Japan Food Database' },
  { name: 'California Roll', brand: null, calories: 255, protein: 9, carbs: 38, fat: 7, fiber: 1, serving_size: 8, serving_name: 'piezas (250g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz para sushi, cangrejo, aguacate, pepino, nori, sésamo', data_source: 'MEXT Japan Food Database' },
  { name: 'Dragon Roll', brand: null, calories: 320, protein: 14, carbs: 38, fat: 12, fiber: 2, serving_size: 8, serving_name: 'piezas (280g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Arroz, camarón tempura, aguacate, anguila, pepino, salsa teriyaki', data_source: 'MEXT Japan Food Database' },
  { name: 'Spicy Tuna Roll', brand: null, calories: 220, protein: 12, carbs: 30, fat: 6, fiber: 1, serving_size: 6, serving_name: 'piezas (200g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Atún picante, arroz para sushi, nori, mayonesa picante, pepino', data_source: 'MEXT Japan Food Database' },
  { name: 'Ramen Tonkotsu', brand: null, calories: 550, protein: 22, carbs: 65, fat: 20, fiber: 3, serving_size: 1, serving_name: 'tazón (600ml)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Fideos ramen, caldo de huesos de cerdo, chashu, huevo marinado, nori, cebollín, brotes de bambú', data_source: 'MEXT Japan Food Database' },
  { name: 'Ramen Shoyu', brand: null, calories: 450, protein: 20, carbs: 58, fat: 14, fiber: 3, serving_size: 1, serving_name: 'tazón (550ml)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Fideos, caldo de pollo, salsa de soya, chashu, huevo, nori, cebollín', data_source: 'MEXT Japan Food Database' },
  { name: 'Ramen Miso', brand: null, calories: 500, protein: 22, carbs: 60, fat: 18, fiber: 4, serving_size: 1, serving_name: 'tazón (600ml)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Fideos, caldo de cerdo, miso, maíz, mantequilla, chashu, brotes de bambú', data_source: 'MEXT Japan Food Database' },
  { name: 'Udon en caldo', brand: null, calories: 320, protein: 10, carbs: 58, fat: 4, fiber: 2, serving_size: 1, serving_name: 'tazón (500ml)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Fideos udon, dashi, soya, mirin, tempura, cebollín, kamaboko', data_source: 'MEXT Japan Food Database' },
  { name: 'Soba fría (Zaru Soba)', brand: null, calories: 280, protein: 12, carbs: 52, fat: 2, fiber: 4, serving_size: 1, serving_name: 'plato (300g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Fideos de trigo sarraceno, salsa tsuyu, wasabi, cebollín, nori', data_source: 'MEXT Japan Food Database' },
  { name: 'Tempura de Camarón y Verduras', brand: null, calories: 380, protein: 12, carbs: 38, fat: 20, fiber: 3, serving_size: 1, serving_name: 'plato (200g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Camarón, calabaza, camote, berenjena, harina tempura, aceite', data_source: 'MEXT Japan Food Database' },
  { name: 'Teriyaki de Salmón', brand: null, calories: 320, protein: 28, carbs: 18, fat: 14, fiber: 0, serving_size: 1, serving_name: 'porción (200g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Salmón, salsa teriyaki, soya, mirin, jengibre, arroz', data_source: 'MEXT Japan Food Database' },
  { name: 'Pollo Teriyaki', brand: null, calories: 290, protein: 25, carbs: 20, fat: 10, fiber: 1, serving_size: 1, serving_name: 'porción (220g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pollo, salsa teriyaki, soya, mirin, arroz, brócoli', data_source: 'MEXT Japan Food Database' },
  { name: 'Gyudon (bowl de res)', brand: null, calories: 480, protein: 22, carbs: 62, fat: 14, fiber: 2, serving_size: 1, serving_name: 'plato (400g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz, res en láminas, cebolla, dashi, soya, mirin, huevo', data_source: 'MEXT Japan Food Database' },
  { name: 'Oyakodon (bowl de pollo y huevo)', brand: null, calories: 420, protein: 22, carbs: 55, fat: 12, fiber: 1, serving_size: 1, serving_name: 'plato (380g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz, pollo, huevo, cebolla, dashi, soya, mirin', data_source: 'MEXT Japan Food Database' },
  { name: 'Katsudon (bowl de cerdo empanizado)', brand: null, calories: 520, protein: 24, carbs: 58, fat: 18, fiber: 1, serving_size: 1, serving_name: 'plato (400g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz, cerdo empanizado, huevo, cebolla, dashi, soya', data_source: 'MEXT Japan Food Database' },
  { name: 'Kare Raisu (arroz con curry)', brand: null, calories: 480, protein: 14, carbs: 65, fat: 16, fiber: 3, serving_size: 1, serving_name: 'plato (400g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Arroz, curry japonés, papa, zanahoria, cerdo, cebolla', data_source: 'MEXT Japan Food Database' },
  { name: 'Okonomiyaki', brand: null, calories: 350, protein: 14, carbs: 38, fat: 16, fiber: 3, serving_size: 1, serving_name: 'porción (250g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Harina, repollo, huevo, cerdo, bonito seco, mayonesa, salsa okonomi', data_source: 'MEXT Japan Food Database' },
  { name: 'Takoyaki', brand: null, calories: 280, protein: 10, carbs: 30, fat: 14, fiber: 1, serving_size: 6, serving_name: 'piezas (150g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Harina, pulpo, huevo, jengibre, bonito seco, mayonesa, salsa', data_source: 'MEXT Japan Food Database' },
  { name: 'Yakitori (brochetas de pollo)', brand: null, calories: 180, protein: 18, carbs: 5, fat: 10, fiber: 0, serving_size: 4, serving_name: 'brochetas (100g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Pollo, salsa tare, sal, carbón', data_source: 'MEXT Japan Food Database' },
  { name: 'Gyoza (empanadillas)', brand: null, calories: 220, protein: 10, carbs: 22, fat: 10, fiber: 1, serving_size: 5, serving_name: 'piezas (120g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa, cerdo molido, repollo, ajo, jengibre, soya', data_source: 'MEXT Japan Food Database' },
  { name: 'Edamame', brand: null, calories: 122, protein: 11, carbs: 9, fat: 5, fiber: 5, serving_size: 1, serving_name: 'porción (100g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Soya verde con sal', data_source: 'MEXT Japan Food Database' },
  { name: 'Onigiri (bola de arroz)', brand: null, calories: 180, protein: 4, carbs: 38, fat: 1, fiber: 0, serving_size: 1, serving_name: 'pieza (120g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Arroz, salmón o umeboshi, nori, sal', data_source: 'MEXT Japan Food Database' },
  { name: 'Mochi de frijol rojo', brand: null, calories: 120, protein: 2, carbs: 25, fat: 0, fiber: 1, serving_size: 1, serving_name: 'pieza (50g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Arroz glutinoso, pasta de frijol rojo (anko)', data_source: 'MEXT Japan Food Database' },
  { name: 'Matcha Latte', brand: null, calories: 120, protein: 5, carbs: 16, fat: 4, fiber: 0, serving_size: 1, serving_name: 'taza (250ml)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Té matcha, leche, azúcar', data_source: 'MEXT Japan Food Database' },
  { name: 'Sashimi de Salmón', brand: null, calories: 130, protein: 20, carbs: 0, fat: 5, fiber: 0, serving_size: 5, serving_name: 'piezas (100g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Salmón fresco, wasabi, jengibre encurtido, soya', data_source: 'MEXT Japan Food Database' },
  { name: 'Sashimi de Atún', brand: null, calories: 120, protein: 23, carbs: 0, fat: 2, fiber: 0, serving_size: 5, serving_name: 'piezas (100g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Atún maguro fresco, wasabi, jengibre, soya', data_source: 'MEXT Japan Food Database' },
  { name: 'Agedashi Tofu', brand: null, calories: 180, protein: 8, carbs: 12, fat: 12, fiber: 1, serving_size: 1, serving_name: 'plato (150g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Tofu firme, almidón, dashi, soya, rábano, jengibre, cebollín', data_source: 'MEXT Japan Food Database' },
  { name: 'Shabu Shabu', brand: null, calories: 350, protein: 22, carbs: 28, fat: 16, fiber: 3, serving_size: 1, serving_name: 'plato (400g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Res en láminas, tofu, verduras, fideos, caldo kombu, salsa ponzu', data_source: 'MEXT Japan Food Database' },

  // ==================== CHINA ====================
  { name: 'Dim Sum: Har Gow (dumpling de camarón)', brand: null, calories: 90, protein: 6, carbs: 12, fat: 2, fiber: 0, serving_size: 3, serving_name: 'piezas (90g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Camarón, almidón de trigo, bambú, aceite de sésamo', data_source: 'Chinese Food Composition Table' },
  { name: 'Dim Sum: Siu Mai', brand: null, calories: 120, protein: 8, carbs: 10, fat: 6, fiber: 0, serving_size: 3, serving_name: 'piezas (90g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Cerdo, camarón, masa de wonton, jengibre, aceite de sésamo', data_source: 'Chinese Food Composition Table' },
  { name: 'Dim Sum: Char Siu Bao', brand: null, calories: 200, protein: 8, carbs: 30, fat: 6, fiber: 1, serving_size: 2, serving_name: 'piezas (120g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Harina, cerdo BBQ, azúcar, soya, hoisin', data_source: 'Chinese Food Composition Table' },
  { name: 'Pato Pekín', brand: null, calories: 380, protein: 22, carbs: 18, fat: 26, fiber: 1, serving_size: 1, serving_name: 'porción (200g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pato asado, crepes, cebollín, pepino, salsa hoisin', data_source: 'Chinese Food Composition Table' },
  { name: 'Pollo Kung Pao', brand: null, calories: 310, protein: 22, carbs: 18, fat: 18, fiber: 2, serving_size: 1, serving_name: 'plato (300g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pollo, cacahuates, chile seco, soya, vinagre, jengibre, ajo', data_source: 'Chinese Food Composition Table' },
  { name: 'Pollo General Tso', brand: null, calories: 420, protein: 20, carbs: 42, fat: 18, fiber: 2, serving_size: 1, serving_name: 'plato (350g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Pollo empanizado, chile, soya, vinagre, azúcar, jengibre', data_source: 'Chinese Food Composition Table' },
  { name: 'Mapo Tofu', brand: null, calories: 250, protein: 14, carbs: 12, fat: 16, fiber: 3, serving_size: 1, serving_name: 'plato (280g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tofu, carne molida de cerdo, doubanjiang, jengibre, ajo, cebollín, aceite de chile', data_source: 'Chinese Food Composition Table' },
  { name: 'Chow Mein', brand: null, calories: 350, protein: 14, carbs: 45, fat: 12, fiber: 3, serving_size: 1, serving_name: 'plato (300g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Fideos, pollo, repollo, zanahoria, brotes de soya, soya, aceite de sésamo', data_source: 'Chinese Food Composition Table' },
  { name: 'Arroz Frito Yangzhou', brand: null, calories: 320, protein: 12, carbs: 45, fat: 10, fiber: 2, serving_size: 1, serving_name: 'plato (300g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz, camarón, cerdo, huevo, chícharos, zanahoria, cebollín', data_source: 'Chinese Food Composition Table' },
  { name: 'Wonton Soup', brand: null, calories: 220, protein: 14, carbs: 22, fat: 8, fiber: 1, serving_size: 1, serving_name: 'tazón (400ml)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Wontons de cerdo y camarón, caldo, cebollín, pak choi', data_source: 'Chinese Food Composition Table' },
  { name: 'Hot Pot (caldero picante)', brand: null, calories: 450, protein: 28, carbs: 15, fat: 30, fiber: 3, serving_size: 1, serving_name: 'plato (500g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Res, mariscos, tofu, verduras, hongos, caldo picante, salsa de sésamo', data_source: 'Chinese Food Composition Table' },
  { name: 'Xiao Long Bao (dumplings de sopa)', brand: null, calories: 180, protein: 10, carbs: 20, fat: 8, fiber: 1, serving_size: 4, serving_name: 'piezas (120g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa, cerdo, caldo gelificado, jengibre, vinagre negro', data_source: 'Chinese Food Composition Table' },
  { name: 'Pekinés de Cerdo Agridulce', brand: null, calories: 380, protein: 18, carbs: 40, fat: 16, fiber: 1, serving_size: 1, serving_name: 'plato (300g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Cerdo, piña, pimiento, cebolla, salsa agridulce, ketchup', data_source: 'Chinese Food Composition Table' },
  { name: 'Baozi de Cerdo', brand: null, calories: 220, protein: 10, carbs: 30, fat: 8, fiber: 2, serving_size: 1, serving_name: 'pieza (120g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Harina, cerdo molido, cebollín, jengibre, soya, levadura', data_source: 'Chinese Food Composition Table' },
  { name: 'Jianbing (crepe chino)', brand: null, calories: 350, protein: 12, carbs: 38, fat: 16, fiber: 2, serving_size: 1, serving_name: 'pieza (200g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Harina de trigo, huevo, cebollín, salsa hoisin, wonton crujiente', data_source: 'Chinese Food Composition Table' },
  { name: 'Dan Dan Noodles', brand: null, calories: 380, protein: 16, carbs: 42, fat: 16, fiber: 3, serving_size: 1, serving_name: 'plato (300g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Fideos, cerdo, pasta de sésamo, chile, soya, cacahuates, cebollín', data_source: 'Chinese Food Composition Table' },
  { name: 'Spring Rolls (rollos de primavera)', brand: null, calories: 220, protein: 6, carbs: 25, fat: 12, fiber: 2, serving_size: 3, serving_name: 'piezas (120g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa de rollo, repollo, zanahoria, champiñón, bambú, soya', data_source: 'Chinese Food Composition Table' },
  { name: 'Té de burbjas clásico', brand: null, calories: 280, protein: 2, carbs: 55, fat: 5, fiber: 0, serving_size: 1, serving_name: 'vaso (500ml)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Té negro, leche, tapioca, azúcar, hielo', data_source: 'Chinese Food Composition Table' },
  { name: 'Pies de huevo (dan ta)', brand: null, calories: 180, protein: 4, carbs: 22, fat: 9, fiber: 0, serving_size: 1, serving_name: 'pieza (80g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Masa quebrada, huevo, leche, azúcar, vainilla', data_source: 'Chinese Food Composition Table' },

  // ==================== INDIA ====================
  { name: 'Pollo Tikka Masala', brand: null, calories: 320, protein: 22, carbs: 12, fat: 22, fiber: 2, serving_size: 1, serving_name: 'plato (250g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pollo, yogur, tikka masala, tomate, crema, cebolla, ajo, jengibre, especias', data_source: 'Indian Food Composition Table' },
  { name: 'Pollo Tandoori', brand: null, calories: 260, protein: 28, carbs: 4, fat: 14, fiber: 0, serving_size: 1, serving_name: 'porción (200g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pollo, yogur, garam masala, chile, cúrcuma, limón', data_source: 'Indian Food Composition Table' },
  { name: 'Butter Chicken (Murgh Makhani)', brand: null, calories: 380, protein: 24, carbs: 14, fat: 26, fiber: 2, serving_size: 1, serving_name: 'plato (280g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pollo, mantequilla, tomate, crema, garam masala, fenogreco', data_source: 'Indian Food Composition Table' },
  { name: 'Biryani de Pollo', brand: null, calories: 420, protein: 22, carbs: 48, fat: 16, fiber: 2, serving_size: 1, serving_name: 'plato (350g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz basmati, pollo, azafrán, yogur, especias, cebolla frita', data_source: 'Indian Food Composition Table' },
  { name: 'Biryani de Cordero', brand: null, calories: 480, protein: 25, carbs: 48, fat: 20, fiber: 2, serving_size: 1, serving_name: 'plato (380g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz basmati, cordero, yogur, azafrán, cardamomo, canela', data_source: 'Indian Food Composition Table' },
  { name: 'Biryani Vegetariano', brand: null, calories: 350, protein: 10, carbs: 52, fat: 12, fiber: 4, serving_size: 1, serving_name: 'plato (350g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Arroz basmati, verduras mixtas, yogur, especias, azafrán', data_source: 'Indian Food Composition Table' },
  { name: 'Palak Paneer', brand: null, calories: 280, protein: 14, carbs: 12, fat: 20, fiber: 4, serving_size: 1, serving_name: 'plato (250g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Paneer, espinaca, tomate, cebolla, ajo, jengibre, garam masala', data_source: 'Indian Food Composition Table' },
  { name: 'Chana Masala', brand: null, calories: 250, protein: 12, carbs: 35, fat: 8, fiber: 8, serving_size: 1, serving_name: 'plato (250g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Garbanzos, tomate, cebolla, ajo, jengibre, chile, comino, cilantro', data_source: 'Indian Food Composition Table' },
  { name: 'Dal Makhani', brand: null, calories: 220, protein: 10, carbs: 25, fat: 10, fiber: 7, serving_size: 1, serving_name: 'plato (200g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Lentejas negras, frijoles rojos, mantequilla, crema, tomate, especias', data_source: 'Indian Food Composition Table' },
  { name: 'Dal Tadka', brand: null, calories: 180, protein: 10, carbs: 22, fat: 6, fiber: 7, serving_size: 1, serving_name: 'plato (200g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Lentejas amarillas, ajo, comino, chile, cilantro, ghee', data_source: 'Indian Food Composition Table' },
  { name: 'Naan con mantequilla', brand: null, calories: 260, protein: 7, carbs: 38, fat: 10, fiber: 1, serving_size: 1, serving_name: 'pieza (90g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Harina, yogur, mantequilla, levadura, sal', data_source: 'Indian Food Composition Table' },
  { name: 'Naan de ajo', brand: null, calories: 280, protein: 7, carbs: 38, fat: 12, fiber: 1, serving_size: 1, serving_name: 'pieza (95g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Harina, ajo, mantequilla, yogur, cilantro', data_source: 'Indian Food Composition Table' },
  { name: 'Roti integral', brand: null, calories: 120, protein: 3, carbs: 20, fat: 3, fiber: 3, serving_size: 1, serving_name: 'pieza (40g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Harina integral, agua, sal', data_source: 'Indian Food Composition Table' },
  { name: 'Samosa', brand: null, calories: 260, protein: 6, carbs: 30, fat: 14, fiber: 3, serving_size: 1, serving_name: 'pieza (100g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa, papa, chícharos, especias, aceite', data_source: 'Indian Food Composition Table' },
  { name: 'Pakora de verduras', brand: null, calories: 220, protein: 6, carbs: 22, fat: 12, fiber: 3, serving_size: 5, serving_name: 'piezas (100g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Harina de garbanzo, cebolla, papa, espinaca, chile, especias', data_source: 'Indian Food Composition Table' },
  { name: 'Aloo Gobi', brand: null, calories: 180, protein: 4, carbs: 25, fat: 8, fiber: 4, serving_size: 1, serving_name: 'plato (200g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Papa, coliflor, cúrcuma, comino, cilantro, chile', data_source: 'Indian Food Composition Table' },
  { name: 'Masala Dosa', brand: null, calories: 300, protein: 8, carbs: 45, fat: 10, fiber: 3, serving_size: 1, serving_name: 'pieza (250g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Masa de arroz y lenteja, papa especiada, chutney, sambar', data_source: 'Indian Food Composition Table' },
  { name: 'Idli (pastel de arroz)', brand: null, calories: 120, protein: 4, carbs: 22, fat: 1, fiber: 1, serving_size: 4, serving_name: 'piezas (100g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Arroz, lenteja urad, chutney de coco, sambar', data_source: 'Indian Food Composition Table' },
  { name: 'Lassi de mango', brand: null, calories: 180, protein: 5, carbs: 32, fat: 4, fiber: 1, serving_size: 1, serving_name: 'vaso (250ml)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Yogur, mango, azúcar, cardamomo', data_source: 'Indian Food Composition Table' },
  { name: 'Lassi dulce', brand: null, calories: 150, protein: 5, carbs: 22, fat: 5, fiber: 0, serving_size: 1, serving_name: 'vaso (250ml)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Yogur, azúcar, cardamomo, agua de rosas', data_source: 'Indian Food Composition Table' },
  { name: 'Gulab Jamun', brand: null, calories: 180, protein: 4, carbs: 25, fat: 8, fiber: 0, serving_size: 2, serving_name: 'piezas (80g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Leche en polvo, harina, ghee, almíbar, cardamomo, azafrán', data_source: 'Indian Food Composition Table' },
  { name: 'Kulfi', brand: null, calories: 220, protein: 6, carbs: 25, fat: 12, fiber: 0, serving_size: 1, serving_name: 'pieza (100g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Leche condensada, pistache, cardamomo, azafrán', data_source: 'Indian Food Composition Table' },
  { name: 'Tikka de Paneer', brand: null, calories: 280, protein: 16, carbs: 8, fat: 20, fiber: 1, serving_size: 1, serving_name: 'porción (200g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Paneer, yogur, especias tikka, pimiento, cebolla', data_source: 'Indian Food Composition Table' },

  // ==================== TAILANDIA ====================
  { name: 'Pad Thai', brand: null, calories: 400, protein: 16, carbs: 50, fat: 14, fiber: 2, serving_size: 1, serving_name: 'plato (300g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Fideos de arroz, camarón/tofu, huevo, brotes de soya, cacahuates, tamarindo, salsa de pescado', data_source: 'INMU Thailand Food Database' },
  { name: 'Pad See Ew', brand: null, calories: 380, protein: 14, carbs: 48, fat: 14, fiber: 2, serving_size: 1, serving_name: 'plato (300g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Fideos anchos de arroz, cerdo, huevo, brócoli chino, soya oscura, ajo', data_source: 'INMU Thailand Food Database' },
  { name: 'Tom Yum Goong', brand: null, calories: 120, protein: 12, carbs: 10, fat: 4, fiber: 1, serving_size: 1, serving_name: 'tazón (300ml)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Camarón, lemongrass, galanga, hojas de lima, chile, champiñón, salsa de pescado, limón', data_source: 'INMU Thailand Food Database' },
  { name: 'Tom Kha Gai', brand: null, calories: 180, protein: 14, carbs: 8, fat: 10, fiber: 1, serving_size: 1, serving_name: 'tazón (300ml)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pollo, leche de coco, lemongrass, galanga, hojas de lima, champiñón, salsa de pescado', data_source: 'INMU Thailand Food Database' },
  { name: 'Curry Verde con Pollo', brand: null, calories: 320, protein: 20, carbs: 15, fat: 22, fiber: 3, serving_size: 1, serving_name: 'plato (300g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pollo, pasta de curry verde, leche de coco, berenjena, albahaca tailandesa, bambú', data_source: 'INMU Thailand Food Database' },
  { name: 'Curry Rojo con Cerdo', brand: null, calories: 350, protein: 18, carbs: 12, fat: 26, fiber: 2, serving_size: 1, serving_name: 'plato (300g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Cerdo, pasta de curry rojo, leche de coco, pimiento, albahaca, bambú', data_source: 'INMU Thailand Food Database' },
  { name: 'Curry Massaman', brand: null, calories: 420, protein: 22, carbs: 30, fat: 24, fiber: 3, serving_size: 1, serving_name: 'plato (350g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Res, papa, cebolla, cacahuates, leche de coco, pasta massaman, tamarindo', data_source: 'INMU Thailand Food Database' },
  { name: 'Curry Panang', brand: null, calories: 380, protein: 20, carbs: 12, fat: 28, fiber: 2, serving_size: 1, serving_name: 'plato (300g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Cerdo, pasta panang, leche de coco, hojas de lima, albahaca', data_source: 'INMU Thailand Food Database' },
  { name: 'Som Tam (ensalada de papaya)', brand: null, calories: 80, protein: 3, carbs: 14, fat: 2, fiber: 3, serving_size: 1, serving_name: 'plato (200g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Papaya verde, chile, ajo, judías verdes, tomate, cacahuates, lima, salsa de pescado', data_source: 'INMU Thailand Food Database' },
  { name: 'Mango Sticky Rice', brand: null, calories: 320, protein: 5, carbs: 55, fat: 10, fiber: 2, serving_size: 1, serving_name: 'plato (250g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz glutinoso, mango, leche de coco, azúcar, sal', data_source: 'INMU Thailand Food Database' },
  { name: 'Khao Pad (arroz frito tailandés)', brand: null, calories: 350, protein: 12, carbs: 45, fat: 14, fiber: 2, serving_size: 1, serving_name: 'plato (300g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Arroz, huevo, cerdo/camarón, cebolla, tomate, salsa de soya, lima', data_source: 'INMU Thailand Food Database' },
  { name: 'Khao Soi', brand: null, calories: 420, protein: 20, carbs: 42, fat: 20, fiber: 3, serving_size: 1, serving_name: 'plato (400ml)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Fideos de huevo, pollo, curry, leche de coco, fideos fritos, cebolla, lima', data_source: 'INMU Thailand Food Database' },
  { name: 'Satay de Pollo', brand: null, calories: 280, protein: 22, carbs: 8, fat: 18, fiber: 1, serving_size: 4, serving_name: 'brochetas (150g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Pollo, cúrcuma, leche de coco, salsa de maní, pepino', data_source: 'INMU Thailand Food Database' },
  { name: 'Spring Rolls Tailandeses (frescos)', brand: null, calories: 120, protein: 6, carbs: 15, fat: 4, fiber: 2, serving_size: 2, serving_name: 'piezas (120g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Papel de arroz, camarón, vermicelli, lechuga, menta, maní', data_source: 'INMU Thailand Food Database' },
  { name: 'Thai Iced Tea', brand: null, calories: 200, protein: 3, carbs: 35, fat: 6, fiber: 0, serving_size: 1, serving_name: 'vaso (350ml)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Té tailandés, leche condensada, azúcar, hielo', data_source: 'INMU Thailand Food Database' },

  // ==================== ESPAÑA ====================
  { name: 'Paella Valenciana', brand: null, calories: 380, protein: 22, carbs: 48, fat: 10, fiber: 2, serving_size: 1, serving_name: 'plato (350g)', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz, pollo, conejo, judía verde, garrofón, tomate, azafrán, romero', data_source: 'BEDCA (Spain)' },
  { name: 'Paella de Mariscos', brand: null, calories: 350, protein: 20, carbs: 45, fat: 8, fiber: 2, serving_size: 1, serving_name: 'plato (350g)', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz, camarón, mejillón, calamar, azafrán, pimiento, tomate, caldo de pescado', data_source: 'BEDCA (Spain)' },
  { name: 'Tortilla Española', brand: null, calories: 220, protein: 10, carbs: 15, fat: 14, fiber: 1, serving_size: 1, serving_name: 'rebanada (120g)', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Huevo, papa, cebolla, aceite de oliva, sal', data_source: 'BEDCA (Spain)' },
  { name: 'Gazpacho Andaluz', brand: null, calories: 70, protein: 2, carbs: 10, fat: 3, fiber: 2, serving_size: 1, serving_name: 'vaso (250ml)', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tomate, pepino, pimiento, ajo, aceite de oliva, vinagre, pan', data_source: 'BEDCA (Spain)' },
  { name: 'Jamón Ibérico', brand: null, calories: 320, protein: 30, carbs: 0, fat: 22, fiber: 0, serving_size: 100, serving_name: 'gramos', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Jamón de cerdo ibérico curado, sal', data_source: 'BEDCA (Spain)' },
  { name: 'Jamón Serrano', brand: null, calories: 280, protein: 32, carbs: 0, fat: 16, fiber: 0, serving_size: 100, serving_name: 'gramos', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Jamón de cerdo curado, sal', data_source: 'BEDCA (Spain)' },
  { name: 'Patatas Bravas', brand: null, calories: 280, protein: 4, carbs: 30, fat: 16, fiber: 3, serving_size: 1, serving_name: 'plato (200g)', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Papa frita, salsa brava (tomate, chile, ajo), alioli', data_source: 'BEDCA (Spain)' },
  { name: 'Croquetas de Jamón', brand: null, calories: 320, protein: 12, carbs: 25, fat: 20, fiber: 1, serving_size: 6, serving_name: 'piezas (150g)', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Bechamel, jamón serrano, pan molido, huevo, aceite', data_source: 'BEDCA (Spain)' },
  { name: 'Gambas al Ajillo', brand: null, calories: 220, protein: 18, carbs: 4, fat: 16, fiber: 0, serving_size: 1, serving_name: 'plato (200g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Camarones, ajo, aceite de oliva, chile seco, perejil', data_source: 'BEDCA (Spain)' },
  { name: 'Pulpo a la Gallega', brand: null, calories: 180, protein: 25, carbs: 5, fat: 6, fiber: 0, serving_size: 1, serving_name: 'plato (200g)', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pulpo, papa, pimentón, aceite de oliva, sal gruesa', data_source: 'BEDCA (Spain)' },
  { name: 'Crema Catalana', brand: null, calories: 240, protein: 5, carbs: 28, fat: 12, fiber: 0, serving_size: 1, serving_name: 'porción (150g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Leche, yema de huevo, azúcar, maicena, cáscara de naranja, canela', data_source: 'BEDCA (Spain)' },
  { name: 'Churros con Chocolate', brand: null, calories: 420, protein: 6, carbs: 55, fat: 20, fiber: 2, serving_size: 6, serving_name: 'piezas (150g)', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Harina, agua, sal, azúcar, chocolate oscuro', data_source: 'BEDCA (Spain)' },
  { name: 'Fabada Asturiana', brand: null, calories: 420, protein: 20, carbs: 35, fat: 24, fiber: 8, serving_size: 1, serving_name: 'plato (350g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Faba, chorizo, morcilla, panceta, azafrán, pimentón', data_source: 'BEDCA (Spain)' },
  { name: 'Cocido Madrileño', brand: null, calories: 520, protein: 30, carbs: 30, fat: 32, fiber: 4, serving_size: 1, serving_name: 'plato (400g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Garbanzo, res, cerdo, chorizo, morcilla, verdura, fideos', data_source: 'BEDCA (Spain)' },
  { name: 'Tapas Mixtas', brand: null, calories: 350, protein: 16, carbs: 20, fat: 22, fiber: 2, serving_size: 1, serving_name: 'plato (250g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Aceitunas, queso manchego, jamón, pan con tomate, boquerones', data_source: 'BEDCA (Spain)' },
  { name: 'Pisto Manchego', brand: null, calories: 120, protein: 3, carbs: 12, fat: 7, fiber: 3, serving_size: 1, serving_name: 'plato (200g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Calabacín, pimiento, tomate, cebolla, ajo, aceite de oliva', data_source: 'BEDCA (Spain)' },
  { name: 'Sangría', brand: null, calories: 120, protein: 0, carbs: 15, fat: 0, fiber: 0, serving_size: 1, serving_name: 'vaso (200ml)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Vino tinto, naranja, limón, manzana, azúcar, canela, soda', data_source: 'BEDCA (Spain)' },

  // ==================== FRANCIA ====================
  { name: 'Croissant', brand: null, calories: 320, protein: 7, carbs: 35, fat: 18, fiber: 1, serving_size: 1, serving_name: 'pieza (70g)', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Harina, mantequilla, huevo, leche, azúcar, levadura, sal', data_source: 'CIQUAL (France)' },
  { name: 'Pain au Chocolat', brand: null, calories: 340, protein: 7, carbs: 38, fat: 18, fiber: 1, serving_size: 1, serving_name: 'pieza (75g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Masa hojaldrada, chocolate negro, mantequilla, huevo', data_source: 'CIQUAL (France)' },
  { name: 'Baguette', brand: null, calories: 270, protein: 9, carbs: 55, fat: 1, fiber: 2, serving_size: 100, serving_name: 'gramos', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Harina, agua, levadura, sal', data_source: 'CIQUAL (France)' },
  { name: 'Boeuf Bourguignon', brand: null, calories: 380, protein: 30, carbs: 12, fat: 22, fiber: 2, serving_size: 1, serving_name: 'plato (300g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Res, vino tinto de Borgoña, zanahoria, cebolla, champiñón, tocino, hierbas', data_source: 'CIQUAL (France)' },
  { name: 'Coq au Vin', brand: null, calories: 340, protein: 28, carbs: 8, fat: 20, fiber: 1, serving_size: 1, serving_name: 'plato (280g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Pollo, vino tinto, champiñón, tocino, cebollitas, zanahoria', data_source: 'CIQUAL (France)' },
  { name: 'Ratatouille', brand: null, calories: 90, protein: 2, carbs: 12, fat: 4, fiber: 4, serving_size: 1, serving_name: 'plato (200g)', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Berenjena, calabacín, pimiento, tomate, cebolla, ajo, hierbas provenzales', data_source: 'CIQUAL (France)' },
  { name: 'Quiche Lorraine', brand: null, calories: 320, protein: 12, carbs: 22, fat: 22, fiber: 1, serving_size: 1, serving_name: 'rebanada (180g)', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa quebrada, huevo, crema, tocino, queso gruyère, nuez moscada', data_source: 'CIQUAL (France)' },
  { name: 'Crème Brûlée', brand: null, calories: 280, protein: 5, carbs: 25, fat: 18, fiber: 0, serving_size: 1, serving_name: 'porción (130g)', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Crema, yema de huevo, azúcar, vainilla', data_source: 'CIQUAL (France)' },
  { name: 'Macaron', brand: null, calories: 95, protein: 2, carbs: 15, fat: 3, fiber: 0, serving_size: 1, serving_name: 'pieza (20g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Almendra, azúcar glass, clara de huevo, relleno (ganache, frambuesa, pistache)', data_source: 'CIQUAL (France)' },
  { name: 'Éclair de Chocolate', brand: null, calories: 280, protein: 6, carbs: 30, fat: 16, fiber: 1, serving_size: 1, serving_name: 'pieza (100g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Masa choux, crema pastelera de chocolate, glaseado de chocolate', data_source: 'CIQUAL (France)' },
  { name: 'Soupe à l\'Oignon', brand: null, calories: 220, protein: 10, carbs: 22, fat: 10, fiber: 2, serving_size: 1, serving_name: 'tazón (350ml)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Cebolla, caldo de res, vino blanco, pan tostado, queso gruyère', data_source: 'CIQUAL (France)' },
  { name: 'Escargot de Bourgogne', brand: null, calories: 180, protein: 14, carbs: 2, fat: 14, fiber: 0, serving_size: 6, serving_name: 'piezas (100g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Caracol, mantequilla con ajo, perejil, chalota', data_source: 'CIQUAL (France)' },
  { name: 'Croque Monsieur', brand: null, calories: 420, protein: 20, carbs: 30, fat: 26, fiber: 1, serving_size: 1, serving_name: 'sándwich (200g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Pan de molde, jamón, queso gruyère, bechamel, mantequilla', data_source: 'CIQUAL (France)' },
  { name: 'Confit de Canard', brand: null, calories: 420, protein: 28, carbs: 0, fat: 34, fiber: 0, serving_size: 1, serving_name: 'porción (180g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Muslo de pato, grasa de pato, sal, pimienta', data_source: 'CIQUAL (France)' },

  // ==================== LÍBANO / MEDIO ORIENTE ====================
  { name: 'Falafel', brand: null, calories: 330, protein: 13, carbs: 32, fat: 18, fiber: 5, serving_size: 5, serving_name: 'piezas (150g)', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Garbanzo, perejil, cebolla, ajo, comino, cilantro, harina', data_source: 'Middle Eastern Food Database' },
  { name: 'Hummus', brand: null, calories: 166, protein: 8, carbs: 14, fat: 10, fiber: 6, serving_size: 100, serving_name: 'gramos', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Garbanzo, tahini, limón, ajo, aceite de oliva', data_source: 'Middle Eastern Food Database' },
  { name: 'Tabbouleh', brand: null, calories: 90, protein: 3, carbs: 12, fat: 4, fiber: 3, serving_size: 1, serving_name: 'plato (150g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Bulgur, perejil, tomate, cebollín, menta, limón, aceite de oliva', data_source: 'Middle Eastern Food Database' },
  { name: 'Shawarma de Pollo', brand: null, calories: 480, protein: 28, carbs: 42, fat: 22, fiber: 3, serving_size: 1, serving_name: 'wrap (300g)', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pollo marinado, pan pita, tahini, pepino, tomate, ajo', data_source: 'Middle Eastern Food Database' },
  { name: 'Shawarma de Cordero', brand: null, calories: 520, protein: 25, carbs: 40, fat: 28, fiber: 3, serving_size: 1, serving_name: 'wrap (300g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Cordero marinado, pan pita, tahini, pepino, tomate, especias', data_source: 'Middle Eastern Food Database' },
  { name: 'Kibbeh', brand: null, calories: 280, protein: 14, carbs: 22, fat: 16, fiber: 2, serving_size: 3, serving_name: 'piezas (150g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Carne de cordero, bulgur, cebolla, especias, piñones', data_source: 'Middle Eastern Food Database' },
  { name: 'Baba Ganoush', brand: null, calories: 120, protein: 3, carbs: 10, fat: 8, fiber: 4, serving_size: 100, serving_name: 'gramos', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Berenjena asada, tahini, ajo, limón, aceite de oliva', data_source: 'Middle Eastern Food Database' },
  { name: 'Fattoush', brand: null, calories: 100, protein: 3, carbs: 12, fat: 5, fiber: 3, serving_size: 1, serving_name: 'ensalada (200g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Lechuga, tomate, pepino, rábano, pan pita frito, sumac, limón', data_source: 'Middle Eastern Food Database' },
  { name: 'Knafeh', brand: null, calories: 380, protein: 10, carbs: 45, fat: 18, fiber: 1, serving_size: 1, serving_name: 'porción (150g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Pasta kataifi, queso, almíbar, pistache, mantequilla', data_source: 'Middle Eastern Food Database' },
  { name: 'Baklava', brand: null, calories: 430, protein: 6, carbs: 45, fat: 26, fiber: 2, serving_size: 1, serving_name: 'pieza (70g)', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa filo, nuez/pistache, mantequilla, almíbar, canela', data_source: 'Middle Eastern Food Database' },

  // ==================== COREA ====================
  { name: 'Bibimbap', brand: null, calories: 420, protein: 18, carbs: 55, fat: 14, fiber: 4, serving_size: 1, serving_name: 'plato (400g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz, carne de res, verduras (espinaca, zanahoria, brotes), huevo, gochujang, sésamo', data_source: 'Korean Food Database' },
  { name: 'Kimchi', brand: null, calories: 20, protein: 1, carbs: 4, fat: 0, fiber: 2, serving_size: 100, serving_name: 'gramos', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Col china, chile en polvo, ajo, jengibre, salsa de pescado, sal', data_source: 'Korean Food Database' },
  { name: 'Bulgogi', brand: null, calories: 320, protein: 25, carbs: 18, fat: 16, fiber: 1, serving_size: 1, serving_name: 'plato (250g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Res en láminas, soya, pera, azúcar, sésamo, ajo, cebollín', data_source: 'Korean Food Database' },
  { name: 'Japchae', brand: null, calories: 280, protein: 6, carbs: 42, fat: 10, fiber: 3, serving_size: 1, serving_name: 'plato (250g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Fideos de camote, espinaca, zanahoria, cebolla, champiñón, soya, sésamo', data_source: 'Korean Food Database' },
  { name: 'Tteokbokki', brand: null, calories: 320, protein: 8, carbs: 55, fat: 8, fiber: 2, serving_size: 1, serving_name: 'plato (300g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pastel de arroz, gochujang, gochugaru, soya, azúcar, huevo', data_source: 'Korean Food Database' },
  { name: 'Samgyeopsal (panceta a la parrilla)', brand: null, calories: 480, protein: 22, carbs: 5, fat: 42, fiber: 0, serving_size: 1, serving_name: 'plato (200g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Panceta de cerdo, lechuga, ajo, ssamjang, kimchi', data_source: 'Korean Food Database' },
  { name: 'Sundubu Jjigae (tofu picante)', brand: null, calories: 220, protein: 16, carbs: 12, fat: 12, fiber: 2, serving_size: 1, serving_name: 'tazón (350ml)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Tofu suave, cerdo/mariscos, gochugaru, cebollín, huevo, calabacín', data_source: 'Korean Food Database' },
  { name: 'Kimbap', brand: null, calories: 350, protein: 12, carbs: 48, fat: 12, fiber: 2, serving_size: 1, serving_name: 'rollo (250g)', category: 'Asiática', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz, nori, espinaca, zanahoria, rábano, huevo, carne', data_source: 'Korean Food Database' },
  { name: 'Soondae (morcilla coreana)', brand: null, calories: 220, protein: 10, carbs: 25, fat: 8, fiber: 1, serving_size: 1, serving_name: 'porción (150g)', category: 'Asiática', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Intestino de cerdo, fideo de vidrio, sangre, cebada, vegetales', data_source: 'Korean Food Database' },

  // ==================== GRECIA ====================
  { name: 'Moussaka', brand: null, calories: 350, protein: 18, carbs: 22, fat: 22, fiber: 4, serving_size: 1, serving_name: 'porción (300g)', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Berenjena, carne molida, tomate, bechamel, parmesano, canela', data_source: 'Greek Food Composition Database' },
  { name: 'Gyros', brand: null, calories: 480, protein: 25, carbs: 42, fat: 22, fiber: 2, serving_size: 1, serving_name: 'wrap (300g)', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Cerdo, pan pita, tzatziki, tomate, cebolla, papas fritas', data_source: 'Greek Food Composition Database' },
  { name: 'Souvlaki', brand: null, calories: 320, protein: 22, carbs: 20, fat: 18, fiber: 2, serving_size: 1, serving_name: 'brocheta (200g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Cerdo/pollo, limón, orégano, aceite de oliva, pita', data_source: 'Greek Food Composition Database' },
  { name: 'Spanakopita', brand: null, calories: 280, protein: 10, carbs: 22, fat: 18, fiber: 2, serving_size: 1, serving_name: 'porción (150g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Masa filo, espinaca, feta, cebollín, eneldo, huevo, mantequilla', data_source: 'Greek Food Composition Database' },
  { name: 'Tzatziki', brand: null, calories: 90, protein: 4, carbs: 6, fat: 6, fiber: 0, serving_size: 100, serving_name: 'gramos', category: 'Mediterránea', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Yogur griego, pepino, ajo, eneldo, limón, aceite de oliva', data_source: 'Greek Food Composition Database' },
  { name: 'Dolmades', brand: null, calories: 180, protein: 4, carbs: 22, fat: 8, fiber: 3, serving_size: 5, serving_name: 'piezas (150g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Hojas de parra, arroz, cebolla, eneldo, limón, aceite de oliva', data_source: 'Greek Food Composition Database' },
  { name: 'Baklava griego', brand: null, calories: 410, protein: 7, carbs: 42, fat: 24, fiber: 2, serving_size: 1, serving_name: 'pieza (70g)', category: 'Mediterránea', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Masa filo, nuez, mantequilla, miel, canela, clavo', data_source: 'Greek Food Composition Database' },
];

async function main() {
  console.log('🌍 Starting massive international food seed...\n');

  const conn = await mysql.createConnection({
    host: 'gateway01.us-east-1.prod.aws.tidbcloud.com',
    port: 4000,
    user: '3ZxNQLB5VbKt56g.root',
    password: '4BLpMj6H4QzcJ8oi',
    database: 'nutriflow',
    ssl: { rejectUnauthorized: true },
  });

  // Check existing
  const [existing] = await conn.query('SELECT name FROM foods') as any;
  const existingNames = new Set(existing.map((r: any) => r.name.toLowerCase()));

  const foodsToInsert = FOODS.filter(f => !existingNames.has(f.name.toLowerCase()));
  console.log(`📊 Total new foods: ${foodsToInsert.length} (skipping ${FOODS.length - foodsToInsert.length} existing)`);

  let inserted = 0;
  let errors = 0;

  for (const food of FOODS) {
    if (existingNames.has(food.name.toLowerCase())) continue;
    try {
      await conn.query(
        `INSERT INTO foods (id, name, brand, calories, protein, carbs, fat, fiber, serving_size, serving_name, category, is_verified, is_priority, is_base_ingredient, ingredients, data_source) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [randomUUID(), food.name, food.brand, food.calories, food.protein, food.carbs, food.fat, food.fiber, food.serving_size, food.serving_name, food.category, food.is_verified, food.is_priority, food.is_base_ingredient, food.ingredients, food.data_source]
      );
      inserted++;
    } catch (err: any) {
      errors++;
      if (errors <= 5) console.error(`  ❌ "${food.name}": ${err.message}`);
    }
  }

  console.log(`\n✅ Inserted: ${inserted}`);
  console.log(`❌ Errors: ${errors}`);

  const [count] = await conn.query('SELECT COUNT(*) as total FROM foods') as any;
  console.log(`📊 Total foods in DB: ${count[0].total}`);

  const [cats] = await conn.query('SELECT category, COUNT(*) as count FROM foods GROUP BY category ORDER BY count DESC LIMIT 20') as any;
  console.log('\n📋 Categories:');
  cats.forEach((c: any) => console.log(`   ${c.category}: ${c.count}`));

  await conn.end();
  console.log('\n🎉 Done!');
}

main().catch(err => { console.error(err); process.exit(1); });
