import mysql from 'mysql2/promise';
import { randomUUID } from 'crypto';

const FOODS = [
  // ==================== SNACKS MEXICANOS ====================
  { name: 'Elote con mayonesa y chile', brand: null, calories: 280, protein: 6, carbs: 32, fat: 14, fiber: 4, serving_size: 1, serving_name: 'pieza (300g)', category: 'snacks', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Elote, mayonesa, queso cotija, chile en polvo, limón', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Esquites', brand: null, calories: 220, protein: 5, carbs: 28, fat: 10, fiber: 3, serving_size: 1, serving_name: 'vaso (250ml)', category: 'snacks', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Granos de elote, epazote, mayonesa, chile, limón, sal', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Churros con azúcar y canela', brand: null, calories: 320, protein: 4, carbs: 42, fat: 16, fiber: 1, serving_size: 3, serving_name: 'piezas (100g)', category: 'snacks', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Harina de trigo, agua, mantequilla, huevo, azúcar, canela, aceite vegetal', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Churros rellenos de cajeta', brand: null, calories: 380, protein: 5, carbs: 50, fat: 18, fiber: 1, serving_size: 2, serving_name: 'piezas (120g)', category: 'snacks', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Harina de trigo, cajeta, azúcar, canela, aceite vegetal', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Tostilocos', brand: null, calories: 290, protein: 5, carbs: 30, fat: 16, fiber: 3, serving_size: 1, serving_name: 'bolsa (85g)', category: 'snacks', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tostitos, cueritos, jícama, pepino, chile, limón, Valentina, cacahuates', data_source: 'Receta tradicional mexicana' },
  { name: 'Dorilocos', brand: null, calories: 310, protein: 5, carbs: 32, fat: 17, fiber: 3, serving_size: 1, serving_name: 'bolsa (90g)', category: 'snacks', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Doritos, cueritos, jícama, pepino, chile, limón, Valentina, cacahuates japoneses', data_source: 'Receta tradicional mexicana' },
  { name: 'Papalote (palomitas de cine mexicanas)', brand: null, calories: 180, protein: 4, carbs: 20, fat: 10, fiber: 3, serving_size: 1, serving_name: 'bolsa chica (50g)', category: 'snacks', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Maíz palomero, mantequilla, sal, chile en polvo', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Gomitas dulces', brand: null, calories: 330, protein: 7, carbs: 75, fat: 0, fiber: 0, serving_size: 1, serving_name: 'bolsa (50g)', category: 'snacks', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Azúcar, jarabe de glucosa, gelatina, ácido cítrico, saborizantes', data_source: 'USDA FoodData Central' },
  { name: 'Pepino con chile y limón', brand: null, calories: 25, protein: 1, carbs: 5, fat: 0, fiber: 1, serving_size: 1, serving_name: 'taza (150g)', category: 'snacks', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pepino, chile en polvo, limón, sal', data_source: 'Receta tradicional mexicana' },
  { name: 'Jícama con chile y limón', brand: null, calories: 40, protein: 1, carbs: 9, fat: 0, fiber: 5, serving_size: 1, serving_name: 'taza (150g)', category: 'snacks', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Jícama, chile en polvo, limón, sal', data_source: 'Receta tradicional mexicana' },
  { name: 'Mango con chile y limón', brand: null, calories: 75, protein: 1, carbs: 18, fat: 0, fiber: 2, serving_size: 1, serving_name: 'taza (150g)', category: 'snacks', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Mango, chile en polvo, limón, sal', data_source: 'Receta tradicional mexicana' },
  { name: 'Sandía con chile y limón', brand: null, calories: 35, protein: 1, carbs: 8, fat: 0, fiber: 0, serving_size: 1, serving_name: 'taza (150g)', category: 'snacks', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Sandía, chile en polvo, limón, sal', data_source: 'Receta tradicional mexicana' },
  { name: 'Cacahuates japoneses', brand: null, calories: 580, protein: 25, carbs: 25, fat: 45, fiber: 8, serving_size: 1, serving_name: 'bolsa (50g)', category: 'snacks', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Cacahuate, harina de trigo, chile, soya, sal', data_source: 'USDA FoodData Central' },
  { name: 'Cacahuates salados', brand: null, calories: 567, protein: 26, carbs: 16, fat: 49, fiber: 8, serving_size: 1, serving_name: 'bolsa (50g)', category: 'snacks', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Cacahuate, sal, aceite vegetal', data_source: 'USDA FoodData Central' },
  { name: 'Papas fritas sabor limón y chile', brand: 'Sabritas', calories: 536, protein: 7, carbs: 53, fat: 33, fiber: 4, serving_size: 1, serving_name: 'bolsa (45g)', category: 'snacks', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Papa, aceite vegetal, sal, chile, ácido cítrico, saborizantes', data_source: 'Etiqueta nutrimental' },
  { name: 'Cheetos Flamin Hot', brand: 'Barcel', calories: 536, protein: 7, carbs: 57, fat: 30, fiber: 2, serving_size: 1, serving_name: 'bolsa (42g)', category: 'snacks', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Harina de maíz, aceite vegetal, sazonador de chile, sal, glutamato monosódico', data_source: 'Etiqueta nutrimental' },
  { name: 'Takis Fuego', brand: 'Barcel', calories: 518, protein: 6, carbs: 57, fat: 29, fiber: 3, serving_size: 1, serving_name: 'bolsa (42g)', category: 'snacks', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Harina de maíz, aceite vegetal, chile, sal, ácido cítrico, glutamato monosódico', data_source: 'Etiqueta nutrimental' },
  { name: 'Ruffles sabor original', brand: 'Sabritas', calories: 529, protein: 6, carbs: 53, fat: 33, fiber: 4, serving_size: 1, serving_name: 'bolsa (45g)', category: 'snacks', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Papa, aceite vegetal, sal', data_source: 'Etiqueta nutrimental' },
  { name: 'Doritos Nacho', brand: 'Sabritas', calories: 500, protein: 6, carbs: 59, fat: 27, fiber: 4, serving_size: 1, serving_name: 'bolsa (42g)', category: 'snacks', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Maíz, aceite vegetal, sazonador de queso, sal, chile', data_source: 'Etiqueta nutrimental' },
  { name: 'Fritos Original', brand: 'Sabritas', calories: 533, protein: 7, carbs: 53, fat: 33, fiber: 4, serving_size: 1, serving_name: 'bolsa (45g)', category: 'snacks', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Maíz, aceite vegetal, sal', data_source: 'Etiqueta nutrimental' },

  // ==================== BEBIDAS MEXICANAS ====================
  { name: 'Atole de chocolate', brand: null, calories: 95, protein: 2, carbs: 16, fat: 3, fiber: 1, serving_size: 1, serving_name: 'taza (250ml)', category: 'bebidas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa de maíz, agua, chocolate, azúcar, canela', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Atole de vainilla', brand: null, calories: 85, protein: 2, carbs: 15, fat: 2, fiber: 0, serving_size: 1, serving_name: 'taza (250ml)', category: 'bebidas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa de maíz, agua, azúcar, vainilla, canela', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Atole de fresa', brand: null, calories: 90, protein: 2, carbs: 16, fat: 2, fiber: 1, serving_size: 1, serving_name: 'taza (250ml)', category: 'bebidas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa de maíz, agua, azúcar, fresa, canela', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Atole de guayaba', brand: null, calories: 95, protein: 2, carbs: 17, fat: 2, fiber: 1, serving_size: 1, serving_name: 'taza (250ml)', category: 'bebidas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa de maíz, agua, azúcar, guayaba, canela', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Agua de horchata', brand: null, calories: 65, protein: 1, carbs: 14, fat: 1, fiber: 0, serving_size: 1, serving_name: 'vaso (250ml)', category: 'bebidas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz, agua, azúcar, canela, leche (opcional)', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Agua de jamaica', brand: null, calories: 50, protein: 0, carbs: 13, fat: 0, fiber: 0, serving_size: 1, serving_name: 'vaso (250ml)', category: 'bebidas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Flor de jamaica, agua, azúcar', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Agua de tamarindo', brand: null, calories: 70, protein: 1, carbs: 17, fat: 0, fiber: 1, serving_size: 1, serving_name: 'vaso (250ml)', category: 'bebidas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tamarindo, agua, azúcar', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Agua de limón', brand: null, calories: 40, protein: 0, carbs: 10, fat: 0, fiber: 0, serving_size: 1, serving_name: 'vaso (250ml)', category: 'bebidas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Limón, agua, azúcar', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Agua de sandía', brand: null, calories: 45, protein: 1, carbs: 11, fat: 0, fiber: 0, serving_size: 1, serving_name: 'vaso (250ml)', category: 'bebidas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Sandía, agua, azúcar', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Agua de melón', brand: null, calories: 50, protein: 1, carbs: 12, fat: 0, fiber: 1, serving_size: 1, serving_name: 'vaso (250ml)', category: 'bebidas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Melón, agua, azúcar', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Agua de papaya', brand: null, calories: 45, protein: 1, carbs: 11, fat: 0, fiber: 1, serving_size: 1, serving_name: 'vaso (250ml)', category: 'bebidas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Papaya, agua, azúcar', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Agua de piña', brand: null, calories: 50, protein: 0, carbs: 12, fat: 0, fiber: 1, serving_size: 1, serving_name: 'vaso (250ml)', category: 'bebidas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Piña, agua, azúcar', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Agua de mango', brand: null, calories: 60, protein: 1, carbs: 14, fat: 0, fiber: 1, serving_size: 1, serving_name: 'vaso (250ml)', category: 'bebidas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Mango, agua, azúcar', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Agua de naranja', brand: null, calories: 45, protein: 1, carbs: 11, fat: 0, fiber: 0, serving_size: 1, serving_name: 'vaso (250ml)', category: 'bebidas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Naranja, agua, azúcar', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Café de olla', brand: null, calories: 15, protein: 0, carbs: 4, fat: 0, fiber: 0, serving_size: 1, serving_name: 'taza (250ml)', category: 'bebidas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Café molido, piloncillo, canela, clavo de olor, agua', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Café americano', brand: null, calories: 2, protein: 0, carbs: 0, fat: 0, fiber: 0, serving_size: 1, serving_name: 'taza (250ml)', category: 'bebidas', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Café molido, agua', data_source: 'USDA FoodData Central' },
  { name: 'Café con leche', brand: null, calories: 55, protein: 3, carbs: 5, fat: 3, fiber: 0, serving_size: 1, serving_name: 'taza (250ml)', category: 'bebidas', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Café, leche entera', data_source: 'USDA FoodData Central' },
  { name: 'Champurrado', brand: null, calories: 120, protein: 3, carbs: 20, fat: 4, fiber: 1, serving_size: 1, serving_name: 'taza (250ml)', category: 'bebidas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa de maíz, chocolate, azúcar, canela, agua', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Tejate', brand: null, calories: 110, protein: 3, carbs: 18, fat: 4, fiber: 2, serving_size: 1, serving_name: 'jícara (250ml)', category: 'bebidas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Maíz tostado, cacao, rosita de cacao, mamey, agua', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Pulque', brand: null, calories: 65, protein: 1, carbs: 6, fat: 0, fiber: 0, serving_size: 1, serving_name: 'vaso (250ml)', category: 'bebidas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Savia fermentada de maguey', data_source: 'Tabla de Composición de Alimentos del INCAP' },

  // ==================== POSTRES MEXICANOS ====================
  { name: 'Flan de huevo', brand: null, calories: 160, protein: 5, carbs: 22, fat: 6, fiber: 0, serving_size: 1, serving_name: 'rebanada (120g)', category: 'postres', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Huevo, leche, azúcar, vainilla, caramelo', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Flan de coco', brand: null, calories: 180, protein: 4, carbs: 24, fat: 8, fiber: 1, serving_size: 1, serving_name: 'rebanada (120g)', category: 'postres', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Huevo, leche, coco rallado, azúcar, vainilla', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Flan napolitano', brand: null, calories: 200, protein: 6, carbs: 24, fat: 9, fiber: 0, serving_size: 1, serving_name: 'rebanada (130g)', category: 'postres', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Huevo, leche, queso crema, azúcar, vainilla', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Arroz con leche', brand: null, calories: 140, protein: 4, carbs: 24, fat: 4, fiber: 0, serving_size: 1, serving_name: 'taza (200g)', category: 'postres', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz, leche, azúcar, canela, pasas', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Capirotada', brand: null, calories: 280, protein: 8, carbs: 42, fat: 10, fiber: 3, serving_size: 1, serving_name: 'rebanada (150g)', category: 'postres', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan, piloncillo, canela, clavo, pasas, cacahuates, nuez, queso, coco', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Cocadas', brand: null, calories: 350, protein: 3, carbs: 45, fat: 18, fiber: 3, serving_size: 1, serving_name: 'pieza (50g)', category: 'postres', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Coco rallado, azúcar, leche condensada, yema de huevo', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Alegrías (amaranto)', brand: null, calories: 420, protein: 12, carbs: 55, fat: 18, fiber: 6, serving_size: 1, serving_name: 'barra (60g)', category: 'postres', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Amaranto, miel de piloncillo, pasas, nuez', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Palanquetas de cacahuate', brand: null, calories: 480, protein: 14, carbs: 45, fat: 28, fiber: 4, serving_size: 1, serving_name: 'pieza (70g)', category: 'postres', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Cacahuate, piloncillo, mantequilla', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Camote enmielado', brand: null, calories: 200, protein: 2, carbs: 42, fat: 4, fiber: 3, serving_size: 1, serving_name: 'pieza (150g)', category: 'postres', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Camote, piloncillo, canela, clavo', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Calabaza en tacha', brand: null, calories: 150, protein: 1, carbs: 35, fat: 1, fiber: 3, serving_size: 1, serving_name: 'rebanada (150g)', category: 'postres', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Calabaza, piloncillo, canela, clavo', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Buñuelos con miel de piloncillo', brand: null, calories: 320, protein: 4, carbs: 45, fat: 14, fiber: 1, serving_size: 2, serving_name: 'piezas (100g)', category: 'postres', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Harina, huevo, manteca, piloncillo, canela, anís', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Marquesita', brand: null, calories: 380, protein: 8, carbs: 40, fat: 20, fiber: 1, serving_size: 1, serving_name: 'pieza (120g)', category: 'postres', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Harina, huevo, queso de bola, Nutella, cajeta', data_source: 'Receta tradicional yucateca' },
  { name: 'Nieva de coco', brand: null, calories: 120, protein: 2, carbs: 22, fat: 3, fiber: 1, serving_size: 1, serving_name: 'vaso (200ml)', category: 'postres', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Coco, leche, azúcar, hielo, canela', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Gazpacho michoacano (fruta con chile)', brand: null, calories: 80, protein: 2, carbs: 17, fat: 0, fiber: 2, serving_size: 1, serving_name: 'vaso (200g)', category: 'postres', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Fruta de temporada, chile, limón, sal', data_source: 'Receta tradicional michoacana' },
  { name: 'Mango bionico', brand: null, calories: 180, protein: 4, carbs: 30, fat: 5, fiber: 2, serving_size: 1, serving_name: 'vaso (250g)', category: 'postres', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Mango, crema, leche condensada, granola, pasas', data_source: 'Receta tradicional mexicana' },

  // ==================== INGREDIENTES BASE ====================
  { name: 'Harina de trigo todo uso', brand: null, calories: 364, protein: 10, carbs: 76, fat: 1, fiber: 3, serving_size: 100, serving_name: 'gramos', category: 'ingredientes', is_verified: 1, is_priority: 1, is_base_ingredient: 1, ingredients: 'Trigo molido', data_source: 'USDA FoodData Central' },
  { name: 'Harina de maíz (Maseca)', brand: 'Maseca', calories: 362, protein: 8, carbs: 77, fat: 2, fiber: 7, serving_size: 100, serving_name: 'gramos', category: 'ingredientes', is_verified: 1, is_priority: 1, is_base_ingredient: 1, ingredients: 'Maíz nixtamalizado molido', data_source: 'USDA FoodData Central' },
  { name: 'Arroz blanco', brand: null, calories: 130, protein: 3, carbs: 28, fat: 0, fiber: 0, serving_size: 100, serving_name: 'gramos', category: 'ingredientes', is_verified: 1, is_priority: 1, is_base_ingredient: 1, ingredients: 'Arroz cocido', data_source: 'USDA FoodData Central' },
  { name: 'Arroz integral', brand: null, calories: 123, protein: 3, carbs: 26, fat: 1, fiber: 2, serving_size: 100, serving_name: 'gramos', category: 'ingredientes', is_verified: 1, is_priority: 1, is_base_ingredient: 1, ingredients: 'Arroz integral cocido', data_source: 'USDA FoodData Central' },
  { name: 'Frijol negro cocido', brand: null, calories: 132, protein: 9, carbs: 24, fat: 1, fiber: 9, serving_size: 100, serving_name: 'gramos', category: 'ingredientes', is_verified: 1, is_priority: 1, is_base_ingredient: 1, ingredients: 'Frijol negro cocido con sal', data_source: 'USDA FoodData Central' },
  { name: 'Frijol de la olla', brand: null, calories: 140, protein: 9, carbs: 25, fat: 1, fiber: 8, serving_size: 100, serving_name: 'gramos', category: 'ingredientes', is_verified: 1, is_priority: 1, is_base_ingredient: 1, ingredients: 'Frijol pinto cocido con caldo', data_source: 'USDA FoodData Central' },
  { name: 'Frijoles refritos', brand: null, calories: 160, protein: 8, carbs: 22, fat: 5, fiber: 7, serving_size: 100, serving_name: 'gramos', category: 'ingredientes', is_verified: 1, is_priority: 1, is_base_ingredient: 1, ingredients: 'Frijol refrito con manteca de cerdo', data_source: 'USDA FoodData Central' },
  { name: 'Aceite vegetal (cártamo)', brand: null, calories: 900, protein: 0, carbs: 0, fat: 100, fiber: 0, serving_size: 100, serving_name: 'ml', category: 'ingredientes', is_verified: 1, is_priority: 1, is_base_ingredient: 1, ingredients: 'Aceite de cártamo', data_source: 'USDA FoodData Central' },
  { name: 'Aceite de oliva', brand: null, calories: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, serving_size: 100, serving_name: 'ml', category: 'ingredientes', is_verified: 1, is_priority: 1, is_base_ingredient: 1, ingredients: 'Aceite de oliva extra virgen', data_source: 'USDA FoodData Central' },
  { name: 'Manteca de cerdo', brand: null, calories: 902, protein: 0, carbs: 0, fat: 100, fiber: 0, serving_size: 100, serving_name: 'gramos', category: 'ingredientes', is_verified: 1, is_priority: 1, is_base_ingredient: 1, ingredients: 'Grasa de cerdo refinada', data_source: 'USDA FoodData Central' },
  { name: 'Azúcar blanca', brand: null, calories: 387, protein: 0, carbs: 100, fat: 0, fiber: 0, serving_size: 100, serving_name: 'gramos', category: 'ingredientes', is_verified: 1, is_priority: 1, is_base_ingredient: 1, ingredients: 'Sacarosa refinada', data_source: 'USDA FoodData Central' },
  { name: 'Piloncillo', brand: null, calories: 383, protein: 0, carbs: 98, fat: 0, fiber: 0, serving_size: 100, serving_name: 'gramos', category: 'ingredientes', is_verified: 1, is_priority: 1, is_base_ingredient: 1, ingredients: 'Jugo de caña de azúcar concentrado', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Sal de mesa', brand: null, calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, serving_size: 100, serving_name: 'gramos', category: 'ingredientes', is_verified: 1, is_priority: 0, is_base_ingredient: 1, ingredients: 'Cloruro de sodio', data_source: 'USDA FoodData Central' },
  { name: 'Chile guajillo seco', brand: null, calories: 270, protein: 13, carbs: 51, fat: 9, fiber: 27, serving_size: 100, serving_name: 'gramos', category: 'ingredientes', is_verified: 1, is_priority: 1, is_base_ingredient: 1, ingredients: 'Chile guajillo deshidratado', data_source: 'USDA FoodData Central' },
  { name: 'Chile ancho seco', brand: null, calories: 281, protein: 12, carbs: 54, fat: 7, fiber: 24, serving_size: 100, serving_name: 'gramos', category: 'ingredientes', is_verified: 1, is_priority: 1, is_base_ingredient: 1, ingredients: 'Chile poblano seco', data_source: 'USDA FoodData Central' },
  { name: 'Chile de árbol seco', brand: null, calories: 310, protein: 13, carbs: 52, fat: 8, fiber: 28, serving_size: 100, serving_name: 'gramos', category: 'ingredientes', is_verified: 1, is_priority: 1, is_base_ingredient: 1, ingredients: 'Chile de árbol deshidratado', data_source: 'USDA FoodData Central' },
  { name: 'Chile chipotle adobado', brand: null, calories: 36, protein: 1, carbs: 5, fat: 1, fiber: 2, serving_size: 15, serving_name: 'chile (15g)', category: 'ingredientes', is_verified: 1, is_priority: 1, is_base_ingredient: 1, ingredients: 'Chile jalapeño ahumado, tomate, vinagre, especias', data_source: 'USDA FoodData Central' },
  { name: 'Comino molido', brand: null, calories: 375, protein: 18, carbs: 44, fat: 22, fiber: 11, serving_size: 100, serving_name: 'gramos', category: 'ingredientes', is_verified: 1, is_priority: 0, is_base_ingredient: 1, ingredients: 'Semilla de comino molida', data_source: 'USDA FoodData Central' },
  { name: 'Canela en polvo', brand: null, calories: 247, protein: 4, carbs: 81, fat: 1, fiber: 53, serving_size: 100, serving_name: 'gramos', category: 'ingredientes', is_verified: 1, is_priority: 0, is_base_ingredient: 1, ingredients: 'Corteza de canela molida', data_source: 'USDA FoodData Central' },
  { name: 'Ajo en polvo', brand: null, calories: 331, protein: 17, carbs: 73, fat: 1, fiber: 9, serving_size: 100, serving_name: 'gramos', category: 'ingredientes', is_verified: 1, is_priority: 0, is_base_ingredient: 1, ingredients: 'Ajo deshidratado molido', data_source: 'USDA FoodData Central' },

  // ==================== COMIDAS COMPLETAS MEXICANAS ====================
  { name: 'Chilaquiles rojos con pollo', brand: null, calories: 450, protein: 22, carbs: 48, fat: 18, fiber: 5, serving_size: 1, serving_name: 'plato (350g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Totopos, salsa de chile rojo, pollo desmenuzado, crema, queso, cebolla', data_source: 'Receta tradicional mexicana' },
  { name: 'Chilaquiles verdes con huevo', brand: null, calories: 420, protein: 18, carbs: 45, fat: 18, fiber: 5, serving_size: 1, serving_name: 'plato (350g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Totopos, salsa verde, huevo, crema, queso, cebolla', data_source: 'Receta tradicional mexicana' },
  { name: 'Enchiladas suizas', brand: null, calories: 520, protein: 25, carbs: 42, fat: 28, fiber: 4, serving_size: 3, serving_name: 'piezas (300g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tortilla, pollo, salsa verde, crema, queso manchego, lechuga', data_source: 'Receta tradicional mexicana' },
  { name: 'Enchiladas rojas', brand: null, calories: 380, protein: 15, carbs: 35, fat: 20, fiber: 4, serving_size: 3, serving_name: 'piezas (300g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tortilla, salsa de chile rojo, pollo, queso, crema, lechuga', data_source: 'Receta tradicional mexicana' },
  { name: 'Enchiladas de mole', brand: null, calories: 480, protein: 20, carbs: 40, fat: 26, fiber: 5, serving_size: 3, serving_name: 'piezas (300g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tortilla, mole, pollo, queso, crema, sésamo', data_source: 'Receta tradicional mexicana' },
  { name: 'Enchiladas de tinga', brand: null, calories: 440, protein: 22, carbs: 38, fat: 22, fiber: 4, serving_size: 3, serving_name: 'piezas (300g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tortilla, tinga de pollo, crema, queso, lechuga', data_source: 'Receta tradicional mexicana' },
  { name: 'Torta de milanesa', brand: null, calories: 650, protein: 30, carbs: 65, fat: 28, fiber: 4, serving_size: 1, serving_name: 'pieza (350g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan, carne empanizada, lechuga, tomate, aguacate, mayonesa, jalapeño', data_source: 'Receta tradicional mexicana' },
  { name: 'Torta de tamal (guajolota)', brand: null, calories: 850, protein: 25, carbs: 95, fat: 40, fiber: 5, serving_size: 1, serving_name: 'pieza (400g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan, tamal, mayonesa, jalapeño', data_source: 'Receta popular CDMX' },
  { name: 'Torta ahogada', brand: null, calories: 550, protein: 25, carbs: 55, fat: 24, fiber: 4, serving_size: 1, serving_name: 'pieza (400g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Birote, carnitas, salsa de chile de árbol, cebolla', data_source: 'Receta tradicional jalisciense' },
  { name: 'Torta de cochinita pibil', brand: null, calories: 620, protein: 28, carbs: 55, fat: 30, fiber: 4, serving_size: 1, serving_name: 'pieza (380g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan, cochinita pibil, cebolla morada, habanero, achiote', data_source: 'Receta tradicional yucateca' },
  { name: 'Torta de pastor', brand: null, calories: 680, protein: 30, carbs: 55, fat: 35, fiber: 3, serving_size: 1, serving_name: 'pieza (380g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan, carne al pastor, piña, cebolla, cilantro, salsa', data_source: 'Receta tradicional mexicana' },
  { name: 'Torta de carnitas', brand: null, calories: 600, protein: 28, carbs: 50, fat: 32, fiber: 3, serving_size: 1, serving_name: 'pieza (380g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan, carnitas, frijol, aguacate, jalapeño, mayonesa', data_source: 'Receta tradicional mexicana' },
  { name: 'Torta de chorizo', brand: null, calories: 620, protein: 26, carbs: 50, fat: 35, fiber: 3, serving_size: 1, serving_name: 'pieza (380g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan, chorizo, frijol, aguacate, queso, jalapeño', data_source: 'Receta tradicional mexicana' },
  { name: 'Torta de pollo', brand: null, calories: 520, protein: 25, carbs: 55, fat: 22, fiber: 4, serving_size: 1, serving_name: 'pieza (350g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan, pollo, lechuga, tomate, aguacate, mayonesa', data_source: 'Receta tradicional mexicana' },
  { name: 'Torta de pierna', brand: null, calories: 550, protein: 28, carbs: 50, fat: 25, fiber: 3, serving_size: 1, serving_name: 'pieza (350g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan, pierna de pavo, lechuga, tomate, aguacate, mayonesa', data_source: 'Receta tradicional mexicana' },
  { name: 'Torta de huevo', brand: null, calories: 450, protein: 20, carbs: 45, fat: 20, fiber: 3, serving_size: 1, serving_name: 'pieza (300g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan, huevo, frijol, aguacate, mayonesa', data_source: 'Receta tradicional mexicana' },
  { name: 'Torta de jamón y queso', brand: null, calories: 480, protein: 22, carbs: 50, fat: 22, fiber: 3, serving_size: 1, serving_name: 'pieza (300g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pan, jamón, queso, lechuga, tomate, mayonesa', data_source: 'Receta tradicional mexicana' },
  { name: 'Sincronizada', brand: null, calories: 420, protein: 22, carbs: 30, fat: 24, fiber: 2, serving_size: 1, serving_name: 'pieza (200g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tortilla de harina, jamón, queso, frijoles', data_source: 'Receta tradicional mexicana' },
  { name: 'Quesadilla de pollo', brand: null, calories: 350, protein: 20, carbs: 30, fat: 18, fiber: 3, serving_size: 1, serving_name: 'pieza (200g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tortilla de maíz, pollo, queso, salsa', data_source: 'Receta tradicional mexicana' },
  { name: 'Quesadilla de champiñón', brand: null, calories: 280, protein: 12, carbs: 30, fat: 14, fiber: 3, serving_size: 1, serving_name: 'pieza (200g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tortilla de maíz, champiñón, queso, salsa', data_source: 'Receta tradicional mexicana' },
  { name: 'Quesadilla de flor de calabaza', brand: null, calories: 260, protein: 10, carbs: 28, fat: 14, fiber: 3, serving_size: 1, serving_name: 'pieza (200g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tortilla de maíz, flor de calabaza, queso, epazote', data_source: 'Receta tradicional mexicana' },
  { name: 'Quesadilla de huitlacoche', brand: null, calories: 280, protein: 10, carbs: 30, fat: 14, fiber: 4, serving_size: 1, serving_name: 'pieza (200g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tortilla de maíz, huitlacoche, queso, epazote', data_source: 'Receta tradicional mexicana' },

  // ==================== SOPAS Y CALDOS ====================
  { name: 'Caldo de pollo', brand: null, calories: 120, protein: 12, carbs: 10, fat: 4, fiber: 1, serving_size: 1, serving_name: 'tazón (350ml)', category: 'sopas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pollo, papa, zanahoria, calabacita, cilantro, cebolla, ajo', data_source: 'Receta tradicional mexicana' },
  { name: 'Caldo de res', brand: null, calories: 180, protein: 15, carbs: 14, fat: 8, fiber: 2, serving_size: 1, serving_name: 'tazón (400ml)', category: 'sopas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Res, papa, zanahoria, chayote, elote, calabacita, cilantro', data_source: 'Receta tradicional mexicana' },
  { name: 'Caldo tlalpeño', brand: null, calories: 200, protein: 18, carbs: 15, fat: 8, fiber: 3, serving_size: 1, serving_name: 'tazón (350ml)', category: 'sopas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pollo, garbanzo, zanahoria, chile chipotle, arroz, aguacate', data_source: 'Receta tradicional mexicana' },
  { name: 'Sopa de fideo', brand: null, calories: 180, protein: 5, carbs: 30, fat: 5, fiber: 2, serving_size: 1, serving_name: 'plato (300g)', category: 'sopas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Fideo, tomate, cebolla, ajo, aceite', data_source: 'Receta tradicional mexicana' },
  { name: 'Sopa de arroz', brand: null, calories: 200, protein: 4, carbs: 35, fat: 6, fiber: 1, serving_size: 1, serving_name: 'plato (200g)', category: 'sopas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Arroz, tomate, cebolla, ajo, caldo de pollo, aceite', data_source: 'Receta tradicional mexicana' },
  { name: 'Sopa de lima', brand: null, calories: 220, protein: 18, carbs: 20, fat: 8, fiber: 2, serving_size: 1, serving_name: 'plato (350ml)', category: 'sopas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pollo, tortilla frita, lima, tomate, cebolla, epazote', data_source: 'Receta tradicional yucateca' },
  { name: 'Pozole rojo', brand: null, calories: 320, protein: 20, carbs: 35, fat: 12, fiber: 4, serving_size: 1, serving_name: 'plato (500ml)', category: 'sopas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Maíz pozolero, cerdo, chile guajillo, orégano, lechuga, rábano, tostadas', data_source: 'Receta tradicional mexicana' },
  { name: 'Pozole verde', brand: null, calories: 290, protein: 18, carbs: 32, fat: 10, fiber: 5, serving_size: 1, serving_name: 'plato (500ml)', category: 'sopas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Maíz pozolero, cerdo, salsa verde, pepita, orégano', data_source: 'Receta tradicional mexicana' },
  { name: 'Pozole blanco', brand: null, calories: 270, protein: 18, carbs: 30, fat: 10, fiber: 3, serving_size: 1, serving_name: 'plato (500ml)', category: 'sopas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Maíz pozolero, cerdo, orégano, lechuga, rábano', data_source: 'Receta tradicional mexicana' },
  { name: 'Menudo', brand: null, calories: 280, protein: 22, carbs: 15, fat: 15, fiber: 3, serving_size: 1, serving_name: 'plato (400ml)', category: 'sopas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Panza de res, maíz pozolero, chile guajillo, orégano, cebolla', data_source: 'Receta tradicional mexicana' },
  { name: 'Birria de res', brand: null, calories: 350, protein: 28, carbs: 10, fat: 22, fiber: 2, serving_size: 1, serving_name: 'plato (350ml)', category: 'sopas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Res, chile guajillo, chile ancho, especias, tortillas', data_source: 'Receta tradicional jalisciense' },
  { name: 'Consomé de pollo (estilo Tijuana)', brand: null, calories: 350, protein: 25, carbs: 30, fat: 14, fiber: 3, serving_size: 1, serving_name: 'plato (450ml)', category: 'sopas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pollo, arroz, fideo, papa, zanahoria, garbanzo, cebolla, cilantro', data_source: 'Receta popular de Tijuana' },
  { name: 'Mole de olla', brand: null, calories: 300, protein: 22, carbs: 20, fat: 15, fiber: 3, serving_size: 1, serving_name: 'plato (400ml)', category: 'sopas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Res, elote, chayote, zanahoria, chile guajillo, arroz', data_source: 'Receta tradicional mexicana' },
  { name: 'Sopa de tortilla', brand: null, calories: 220, protein: 10, carbs: 28, fat: 8, fiber: 3, serving_size: 1, serving_name: 'plato (350ml)', category: 'sopas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tortilla frita, tomate, chile pasilla, aguacate, queso, crema', data_source: 'Receta tradicional mexicana' },

  // ==================== GUISADOS ====================
  { name: 'Pollo en mole poblano', brand: null, calories: 480, protein: 30, carbs: 25, fat: 30, fiber: 4, serving_size: 1, serving_name: 'porción (250g)', category: 'guisados', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pollo, chile mulato, chile ancho, chocolate, almendra, ajonjolí, especias', data_source: 'Receta tradicional poblana' },
  { name: 'Pollo en salsa verde', brand: null, calories: 320, protein: 28, carbs: 10, fat: 18, fiber: 3, serving_size: 1, serving_name: 'porción (250g)', category: 'guisados', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pollo, tomate verde, chile serrano, cebolla, ajo, cilantro', data_source: 'Receta tradicional mexicana' },
  { name: 'Pollo en salsa roja', brand: null, calories: 300, protein: 28, carbs: 8, fat: 16, fiber: 2, serving_size: 1, serving_name: 'porción (250g)', category: 'guisados', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pollo, tomate rojo, chile de árbol, cebolla, ajo', data_source: 'Receta tradicional mexicana' },
  { name: 'Pollo en tinga', brand: null, calories: 340, protein: 25, carbs: 12, fat: 22, fiber: 2, serving_size: 1, serving_name: 'porción (250g)', category: 'guisados', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pollo, chipotle, tomate, cebolla, ajo, orégano', data_source: 'Receta tradicional mexicana' },
  { name: 'Cochinita pibil', brand: null, calories: 380, protein: 28, carbs: 15, fat: 24, fiber: 3, serving_size: 1, serving_name: 'porción (250g)', category: 'guisados', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Cerdo, achiote, naranja agria, especias, hoja de plátano', data_source: 'Receta tradicional yucateca' },
  { name: 'Chicharrón en salsa verde', brand: null, calories: 350, protein: 20, carbs: 12, fat: 25, fiber: 3, serving_size: 1, serving_name: 'porción (200g)', category: 'guisados', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Chicharrón de cerdo, tomate verde, chile serrano, cebolla', data_source: 'Receta tradicional mexicana' },
  { name: 'Chicharrón en salsa roja', brand: null, calories: 340, protein: 18, carbs: 10, fat: 25, fiber: 2, serving_size: 1, serving_name: 'porción (200g)', category: 'guisados', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Chicharrón de cerdo, tomate rojo, chile guajillo, cebolla', data_source: 'Receta tradicional mexicana' },
  { name: 'Carne molida con papa', brand: null, calories: 320, protein: 22, carbs: 20, fat: 18, fiber: 2, serving_size: 1, serving_name: 'porción (250g)', category: 'guisados', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Carne de res molida, papa, tomate, cebolla, ajo', data_source: 'Receta tradicional mexicana' },
  { name: 'Bistec encebollado', brand: null, calories: 380, protein: 32, carbs: 15, fat: 22, fiber: 2, serving_size: 1, serving_name: 'porción (250g)', category: 'guisados', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Bistec de res, cebolla, tomate, chile', data_source: 'Receta tradicional mexicana' },
  { name: 'Carne adobada', brand: null, calories: 350, protein: 28, carbs: 10, fat: 22, fiber: 2, serving_size: 1, serving_name: 'porción (250g)', category: 'guisados', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Cerdo, chile guajillo, vinagre, especias, ajo', data_source: 'Receta tradicional mexicana' },
  { name: 'Rajas con crema', brand: null, calories: 180, protein: 5, carbs: 10, fat: 14, fiber: 2, serving_size: 1, serving_name: 'porción (150g)', category: 'guisados', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Chile poblano, crema, queso, cebolla, ajo', data_source: 'Receta tradicional mexicana' },
  { name: 'Rajas con queso', brand: null, calories: 220, protein: 12, carbs: 12, fat: 14, fiber: 2, serving_size: 1, serving_name: 'porción (150g)', category: 'guisados', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Chile poblano, queso manchego, cebolla, ajo', data_source: 'Receta tradicional mexicana' },
  { name: 'Huevos a la mexicana', brand: null, calories: 240, protein: 14, carbs: 8, fat: 16, fiber: 2, serving_size: 2, serving_name: 'huevos (200g)', category: 'guisados', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Huevo, tomate, cebolla, chile serrano', data_source: 'Receta tradicional mexicana' },
  { name: 'Huevos divorciados', brand: null, calories: 320, protein: 18, carbs: 20, fat: 20, fiber: 3, serving_size: 2, serving_name: 'huevos (300g)', category: 'guisados', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Huevo, tortilla, salsa roja, salsa verde, frijol', data_source: 'Receta tradicional mexicana' },
  { name: 'Huevos rancheros', brand: null, calories: 380, protein: 18, carbs: 25, fat: 24, fiber: 4, serving_size: 2, serving_name: 'huevos (300g)', category: 'guisados', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Huevo, tortilla, salsa roja, frijol, aguacate', data_source: 'Receta tradicional mexicana' },
  { name: 'Huevos motuleños', brand: null, calories: 420, protein: 20, carbs: 35, fat: 24, fiber: 5, serving_size: 1, serving_name: 'plato (350g)', category: 'guisados', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Huevo, tortilla, frijol, salsa, jamón, chícharos, plátano frito, queso', data_source: 'Receta tradicional yucateca' },

  // ==================== MARISCOS ====================
  { name: 'Ceviche de camarón', brand: null, calories: 120, protein: 18, carbs: 10, fat: 2, fiber: 1, serving_size: 1, serving_name: 'vaso (250g)', category: 'mariscos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Camarón, limón, tomate, cebolla, cilantro, pepino, aguacate', data_source: 'Receta tradicional mexicana' },
  { name: 'Ceviche de pescado', brand: null, calories: 110, protein: 16, carbs: 10, fat: 2, fiber: 1, serving_size: 1, serving_name: 'vaso (250g)', category: 'mariscos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pescado, limón, tomate, cebolla, cilantro, pepino, aguacate', data_source: 'Receta tradicional mexicana' },
  { name: 'Aguachile de camarón', brand: null, calories: 140, protein: 18, carbs: 8, fat: 4, fiber: 1, serving_size: 1, serving_name: 'plato (250g)', category: 'mariscos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Camarón, limón, chile serrano, pepino, cebolla morada', data_source: 'Receta tradicional sinaloense' },
  { name: 'Coctel de camarón', brand: null, calories: 180, protein: 15, carbs: 15, fat: 6, fiber: 1, serving_size: 1, serving_name: 'vaso (300ml)', category: 'mariscos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Camarón, cátsup, limón, aguacate, cebolla, cilantro', data_source: 'Receta tradicional mexicana' },
  { name: 'Tostada de ceviche', brand: null, calories: 200, protein: 12, carbs: 25, fat: 6, fiber: 2, serving_size: 1, serving_name: 'tostada (120g)', category: 'mariscos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tostada, ceviche, aguacate, salsa, galletas', data_source: 'Receta tradicional mexicana' },
  { name: 'Camarones al mojo de ajo', brand: null, calories: 280, protein: 25, carbs: 5, fat: 18, fiber: 0, serving_size: 1, serving_name: 'porción (200g)', category: 'mariscos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Camarón, ajo, mantequilla, aceite, chile seco', data_source: 'Receta tradicional mexicana' },
  { name: 'Filete de pescado empanizado', brand: null, calories: 320, protein: 22, carbs: 20, fat: 18, fiber: 1, serving_size: 1, serving_name: 'filete (200g)', category: 'mariscos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pescado, harina, huevo, pan molido, aceite', data_source: 'USDA FoodData Central' },
  { name: 'Filete de pescado a la plancha', brand: null, calories: 160, protein: 28, carbs: 0, fat: 4, fiber: 0, serving_size: 1, serving_name: 'filete (180g)', category: 'mariscos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Pescado, limón, sal, aceite de oliva', data_source: 'USDA FoodData Central' },
  { name: 'Pulpo a la gallega', brand: null, calories: 180, protein: 25, carbs: 5, fat: 6, fiber: 0, serving_size: 1, serving_name: 'porción (200g)', category: 'mariscos', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Pulpo, papa, pimentón, aceite de oliva, sal', data_source: 'USDA FoodData Central' },
  { name: 'Tostada de atún', brand: null, calories: 220, protein: 20, carbs: 18, fat: 8, fiber: 2, serving_size: 1, serving_name: 'tostada (120g)', category: 'mariscos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tostada, atún fresco, aguacate, soya, sésamo, cebollín', data_source: 'Receta fusión mexicana' },
  { name: 'Tostada de pata', brand: null, calories: 220, protein: 10, carbs: 22, fat: 10, fiber: 2, serving_size: 1, serving_name: 'tostada (120g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tostada, pata de res, lechuga, crema, queso, salsa', data_source: 'Receta tradicional mexicana' },
  { name: 'Tostada de tinga', brand: null, calories: 250, protein: 14, carbs: 22, fat: 12, fiber: 3, serving_size: 1, serving_name: 'tostada (120g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tostada, tinga de pollo, lechuga, crema, queso', data_source: 'Receta tradicional mexicana' },
  { name: 'Tostada de ceviche de pulpo', brand: null, calories: 210, protein: 14, carbs: 20, fat: 8, fiber: 2, serving_size: 1, serving_name: 'tostada (120g)', category: 'mariscos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tostada, pulpo, limón, tomate, cebolla, aguacate', data_source: 'Receta tradicional mexicana' },

  // ==================== FRUTAS TROPICALES ====================
  { name: 'Mamey', brand: null, calories: 135, protein: 1, carbs: 35, fat: 1, fiber: 5, serving_size: 100, serving_name: 'gramos', category: 'frutas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Mamey sapote', data_source: 'USDA FoodData Central' },
  { name: 'Zapote negro', brand: null, calories: 120, protein: 1, carbs: 32, fat: 0, fiber: 4, serving_size: 100, serving_name: 'gramos', category: 'frutas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Zapote negro', data_source: 'USDA FoodData Central' },
  { name: 'Zapote blanco', brand: null, calories: 90, protein: 1, carbs: 24, fat: 0, fiber: 3, serving_size: 100, serving_name: 'gramos', category: 'frutas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Zapote blanco', data_source: 'USDA FoodData Central' },
  { name: 'Chirimoya', brand: null, calories: 95, protein: 2, carbs: 23, fat: 0, fiber: 4, serving_size: 100, serving_name: 'gramos', category: 'frutas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Chirimoya', data_source: 'USDA FoodData Central' },
  { name: 'Guanábana', brand: null, calories: 66, protein: 1, carbs: 17, fat: 0, fiber: 3, serving_size: 100, serving_name: 'gramos', category: 'frutas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Guanábana', data_source: 'USDA FoodData Central' },
  { name: 'Mamey', brand: null, calories: 135, protein: 1, carbs: 35, fat: 1, fiber: 5, serving_size: 100, serving_name: 'gramos', category: 'frutas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Mamey sapote', data_source: 'USDA FoodData Central' },
  { name: 'Ciruela mexicana', brand: null, calories: 46, protein: 1, carbs: 11, fat: 0, fiber: 2, serving_size: 100, serving_name: 'gramos', category: 'frutas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Ciruela mexicana', data_source: 'USDA FoodData Central' },
  { name: 'Tejocote', brand: null, calories: 42, protein: 0, carbs: 11, fat: 0, fiber: 4, serving_size: 100, serving_name: 'gramos', category: 'frutas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tejocote', data_source: 'USDA FoodData Central' },
  { name: 'Capulín', brand: null, calories: 50, protein: 1, carbs: 12, fat: 0, fiber: 2, serving_size: 100, serving_name: 'gramos', category: 'frutas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Capulín', data_source: 'USDA FoodData Central' },
  { name: 'Tuna (nopal)', brand: null, calories: 41, protein: 1, carbs: 10, fat: 0, fiber: 4, serving_size: 100, serving_name: 'gramos', category: 'frutas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tuna roja o verde', data_source: 'USDA FoodData Central' },
  { name: 'Guayaba', brand: null, calories: 68, protein: 3, carbs: 14, fat: 1, fiber: 5, serving_size: 100, serving_name: 'gramos', category: 'frutas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Guayaba', data_source: 'USDA FoodData Central' },
  { name: 'Chayote', brand: null, calories: 19, protein: 1, carbs: 4, fat: 0, fiber: 2, serving_size: 100, serving_name: 'gramos', category: 'verduras', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Chayote', data_source: 'USDA FoodData Central' },

  // ==================== VERDURAS MEXICANAS ====================
  { name: 'Nopal asado', brand: null, calories: 16, protein: 1, carbs: 3, fat: 0, fiber: 2, serving_size: 100, serving_name: 'gramos', category: 'verduras', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Nopal tierno asado', data_source: 'USDA FoodData Central' },
  { name: 'Nopales en ensalada', brand: null, calories: 25, protein: 1, carbs: 4, fat: 0, fiber: 3, serving_size: 1, serving_name: 'taza (150g)', category: 'verduras', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Nopales, tomate, cebolla, cilantro, limón', data_source: 'Receta tradicional mexicana' },
  { name: 'Huitlacoche (hongo de maíz)', brand: null, calories: 55, protein: 5, carbs: 8, fat: 1, fiber: 2, serving_size: 100, serving_name: 'gramos', category: 'verduras', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Huitlacoche fresco', data_source: 'USDA FoodData Central' },
  { name: 'Quelites', brand: null, calories: 25, protein: 3, carbs: 3, fat: 0, fiber: 3, serving_size: 100, serving_name: 'gramos', category: 'verduras', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Quelites tiernos', data_source: 'USDA FoodData Central' },
  { name: 'Huauzontles', brand: null, calories: 30, protein: 4, carbs: 4, fat: 0, fiber: 3, serving_size: 100, serving_name: 'gramos', category: 'verduras', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Huauzontles', data_source: 'USDA FoodData Central' },
  { name: 'Flor de calabaza', brand: null, calories: 15, protein: 1, carbs: 3, fat: 0, fiber: 1, serving_size: 100, serving_name: 'gramos', category: 'verduras', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Flor de calabaza', data_source: 'USDA FoodData Central' },
  { name: 'Epazote', brand: null, calories: 32, protein: 2, carbs: 7, fat: 0, fiber: 4, serving_size: 100, serving_name: 'gramos', category: 'verduras', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Epazote fresco', data_source: 'USDA FoodData Central' },

  // ==================== SALSAS ====================
  { name: 'Salsa verde cruda', brand: null, calories: 20, protein: 1, carbs: 3, fat: 1, fiber: 1, serving_size: 30, serving_name: 'cucharada (30g)', category: 'salsas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tomate verde, chile serrano, cebolla, cilantro, sal', data_source: 'Receta tradicional mexicana' },
  { name: 'Salsa verde cocida', brand: null, calories: 18, protein: 1, carbs: 3, fat: 0, fiber: 1, serving_size: 30, serving_name: 'cucharada (30g)', category: 'salsas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tomate verde cocido, chile, cebolla, cilantro, sal', data_source: 'Receta tradicional mexicana' },
  { name: 'Salsa roja de molcajete', brand: null, calories: 15, protein: 1, carbs: 3, fat: 0, fiber: 1, serving_size: 30, serving_name: 'cucharada (30g)', category: 'salsas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Jitomate, chile serrano, cebolla, ajo, sal', data_source: 'Receta tradicional mexicana' },
  { name: 'Pico de gallo', brand: null, calories: 12, protein: 1, carbs: 2, fat: 0, fiber: 1, serving_size: 30, serving_name: 'cucharada (30g)', category: 'salsas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Jitomate, cebolla, chile serrano, cilantro, limón', data_source: 'Receta tradicional mexicana' },
  { name: 'Guacamole', brand: null, calories: 90, protein: 1, carbs: 5, fat: 8, fiber: 3, serving_size: 30, serving_name: 'cucharada (45g)', category: 'salsas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Aguacate, tomate, cebolla, chile, cilantro, limón, sal', data_source: 'Receta tradicional mexicana' },
  { name: 'Salsa de chile de árbol', brand: null, calories: 10, protein: 0, carbs: 2, fat: 0, fiber: 0, serving_size: 30, serving_name: 'cucharada (30g)', category: 'salsas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Chile de árbol, tomate, ajo, sal', data_source: 'Receta tradicional mexicana' },
  { name: 'Salsa macha', brand: null, calories: 120, protein: 3, carbs: 2, fat: 12, fiber: 1, serving_size: 30, serving_name: 'cucharada (30g)', category: 'salsas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Chile seco, aceite, ajonjolí, cacahuate, ajo', data_source: 'Receta tradicional veracruzana' },
  { name: 'Crema con chile', brand: null, calories: 80, protein: 2, carbs: 4, fat: 6, fiber: 0, serving_size: 30, serving_name: 'cucharada (30g)', category: 'salsas', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Crema, chile jalapeño', data_source: 'Receta tradicional mexicana' },

  // ==================== BOTANAS ====================
  { name: 'Totopos con guacamole', brand: null, calories: 320, protein: 6, carbs: 30, fat: 20, fiber: 5, serving_size: 1, serving_name: 'porción (150g)', category: 'botanas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Totopos de maíz, guacamole', data_source: 'Receta tradicional mexicana' },
  { name: 'Totopos con frijoles', brand: null, calories: 280, protein: 10, carbs: 35, fat: 10, fiber: 7, serving_size: 1, serving_name: 'porción (150g)', category: 'botanas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Totopos, frijoles refritos, queso', data_source: 'Receta tradicional mexicana' },
  { name: 'Nachos con queso', brand: null, calories: 400, protein: 12, carbs: 35, fat: 24, fiber: 3, serving_size: 1, serving_name: 'porción (150g)', category: 'botanas', is_verified: 1, is_priority: 0, is_base_ingredient: 0, ingredients: 'Totopos, queso fundido, jalapeño', data_source: 'Receta tradicional mexicana' },
  { name: 'Elote preparado (en vaso)', brand: null, calories: 250, protein: 6, carbs: 30, fat: 12, fiber: 4, serving_size: 1, serving_name: 'vaso (250g)', category: 'snacks', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Elote, mayonesa, queso, chile, limón', data_source: 'Receta popular mexicana' },
  { name: 'Esquites (en vaso)', brand: null, calories: 220, protein: 5, carbs: 28, fat: 10, fiber: 3, serving_size: 1, serving_name: 'vaso (250ml)', category: 'snacks', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Granos de elote, epazote, mayonesa, queso, chile', data_source: 'Receta popular mexicana' },
  { name: 'Tostada de ceviche de camarón', brand: null, calories: 220, protein: 14, carbs: 22, fat: 8, fiber: 2, serving_size: 1, serving_name: 'tostada (120g)', category: 'mariscos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tostada, ceviche de camarón, aguacate, salsa', data_source: 'Receta tradicional mexicana' },

  // ==================== DESAYUNOS MEXICANOS ====================
  { name: 'Molletes', brand: null, calories: 380, protein: 18, carbs: 42, fat: 14, fiber: 4, serving_size: 2, serving_name: 'piezas (200g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Bolillo, frijoles, queso, pico de gallo', data_source: 'Receta tradicional mexicana' },
  { name: 'Chilaquiles con huevo', brand: null, calories: 420, protein: 18, carbs: 40, fat: 22, fiber: 4, serving_size: 1, serving_name: 'plato (350g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Totopos, salsa, huevo, crema, queso', data_source: 'Receta tradicional mexicana' },
  { name: 'Tamales de pollo (verde)', brand: null, calories: 280, protein: 12, carbs: 30, fat: 12, fiber: 3, serving_size: 1, serving_name: 'tamal (180g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa, pollo, salsa verde, hoja de maíz', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Tamales de pollo (rojo)', brand: null, calories: 290, protein: 12, carbs: 30, fat: 14, fiber: 3, serving_size: 1, serving_name: 'tamal (180g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa, pollo, chile rojo, hoja de maíz', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Tamales de dulce', brand: null, calories: 240, protein: 4, carbs: 35, fat: 10, fiber: 2, serving_size: 1, serving_name: 'tamal (150g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa, azúcar, pasas, manteca, hoja de maíz', data_source: 'Tabla de Composición de Alimentos del INCAP' },
  { name: 'Tamales oaxaqueños (mole negro)', brand: null, calories: 320, protein: 14, carbs: 28, fat: 18, fiber: 3, serving_size: 1, serving_name: 'tamal (200g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Masa, mole negro, pollo, hoja de plátano', data_source: 'Receta tradicional oaxaqueña' },
  { name: 'Tamales de elote', brand: null, calories: 200, protein: 5, carbs: 30, fat: 8, fiber: 2, serving_size: 1, serving_name: 'tamal (150g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Elote molido, azúcar, mantequilla, hoja de maíz', data_source: 'Tabla de Composición de Alimentos del INCAP' },

  // ==================== COMIDA RÁPIDA MEXICANA ====================
  { name: 'Burrito de carne asada', brand: null, calories: 650, protein: 32, carbs: 55, fat: 32, fiber: 5, serving_size: 1, serving_name: 'pieza (350g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tortilla de harina, carne asada, frijol, queso, guacamole, crema', data_source: 'Receta tradicional mexicana' },
  { name: 'Burrito de pollo', brand: null, calories: 580, protein: 30, carbs: 50, fat: 28, fiber: 5, serving_size: 1, serving_name: 'pieza (350g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tortilla de harina, pollo, frijol, queso, lechuga, crema', data_source: 'Receta tradicional mexicana' },
  { name: 'Burrito de carnitas', brand: null, calories: 680, protein: 28, carbs: 55, fat: 36, fiber: 5, serving_size: 1, serving_name: 'pieza (350g)', category: 'antojitos', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Tortilla de harina, carnitas, frijol, queso, guacamole', data_source: 'Receta tradicional mexicana' },
  { name: 'Queso fundido con chorizo', brand: null, calories: 420, protein: 22, carbs: 8, fat: 35, fiber: 0, serving_size: 1, serving_name: 'porción (200g)', category: 'botanas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Queso, chorizo, tortillas de maíz', data_source: 'Receta tradicional mexicana' },
  { name: 'Queso fundido con champiñón', brand: null, calories: 350, protein: 20, carbs: 10, fat: 28, fiber: 1, serving_size: 1, serving_name: 'porción (200g)', category: 'botanas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Queso, champiñón, tortillas de maíz', data_source: 'Receta tradicional mexicana' },
  { name: 'Nachos con todo', brand: null, calories: 550, protein: 20, carbs: 45, fat: 32, fiber: 5, serving_size: 1, serving_name: 'porción (300g)', category: 'botanas', is_verified: 1, is_priority: 1, is_base_ingredient: 0, ingredients: 'Totopos, queso, guacamole, crema, jalapeño, frijol, carne', data_source: 'Receta tradicional mexicana' },
];

async function main() {
  console.log('🍽️  Starting massive food seed...\n');

  const conn = await mysql.createConnection({
    host: 'gateway01.us-east-1.prod.aws.tidbcloud.com',
    port: 4000,
    user: '3ZxNQLB5VbKt56g.root',
    password: '4BLpMj6H4QzcJ8oi',
    database: 'nutriflow',
    ssl: { rejectUnauthorized: true },
  });

  // Check if table exists
  const [tables] = await conn.query("SHOW TABLES LIKE 'foods'");
  if ((tables as any[]).length === 0) {
    console.log('❌ foods table does not exist');
    await conn.end();
    return;
  }

  // Get existing food names to avoid duplicates
  const [existing] = await conn.query('SELECT name FROM foods') as any;
  const existingNames = new Set(existing.map((r: any) => r.name.toLowerCase()));

  const foodsToInsert = FOODS.filter(f => !existingNames.has(f.name.toLowerCase()));
  console.log(`📊 Total foods to insert: ${foodsToInsert.length} (skipping ${FOODS.length - foodsToInsert.length} existing)`);

  let inserted = 0;
  let skipped = 0;

  for (const food of FOODS) {
    if (existingNames.has(food.name.toLowerCase())) {
      skipped++;
      continue;
    }

    try {
      await conn.query(
        `INSERT INTO foods (id, name, brand, calories, protein, carbs, fat, fiber, serving_size, serving_name, category, is_verified, is_priority, is_base_ingredient, ingredients, data_source) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [randomUUID(), food.name, food.brand, food.calories, food.protein, food.carbs, food.fat, food.fiber, food.serving_size, food.serving_name, food.category, food.is_verified, food.is_priority, food.is_base_ingredient, food.ingredients, food.data_source]
      );
      inserted++;
    } catch (err: any) {
      console.error(`  ❌ Error inserting "${food.name}": ${err.message}`);
    }
  }

  console.log(`\n✅ Results:`);
  console.log(`   ✅ Inserted: ${inserted}`);
  console.log(`   ⏭️  Skipped: ${skipped}`);

  // Show final count
  const [count] = await conn.query('SELECT COUNT(*) as total FROM foods') as any;
  console.log(`   📊 Total foods in DB: ${count[0].total}`);

  // Show category breakdown
  const [cats] = await conn.query('SELECT category, COUNT(*) as count FROM foods GROUP BY category ORDER BY count DESC LIMIT 15') as any;
  console.log('\n📋 Top categories:');
  cats.forEach((c: any) => console.log(`   ${c.category}: ${c.count}`));

  await conn.end();
  console.log('\n🎉 Done!');
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
